// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable CS1591, CS1573, CS0465, CS0649, CS8019, CS1570, CS1584, CS1658
namespace Windows.Win32
{
    using global::System;
    using global::System.Diagnostics;
    using global::System.Runtime.CompilerServices;
    using global::System.Runtime.InteropServices;
    using win32 = global::Windows.Win32;

    namespace System.SystemServices
    {
        internal partial struct DECIMAL
        {
            internal ushort wReserved;
            internal win32.System.SystemServices.DECIMAL._Anonymous1_e__Union Anonymous1;
            internal uint Hi32;
            internal win32.System.SystemServices.DECIMAL._Anonymous2_e__Union Anonymous2;
            [StructLayout(LayoutKind.Explicit)]
            internal partial struct _Anonymous1_e__Union
            {
                [FieldOffset(0)]
                internal win32.System.SystemServices.DECIMAL._Anonymous1_e__Union._Anonymous_e__Struct Anonymous;
                [FieldOffset(0)]
                internal ushort signscale;
                internal partial struct _Anonymous_e__Struct
                {
                    internal byte scale;
                    internal byte sign;
                }
            }

            [StructLayout(LayoutKind.Explicit)]
            internal partial struct _Anonymous2_e__Union
            {
                [FieldOffset(0)]
                internal win32.System.SystemServices.DECIMAL._Anonymous2_e__Union._Anonymous_e__Struct Anonymous;
                [FieldOffset(0)]
                internal ulong Lo64;
                internal partial struct _Anonymous_e__Struct
                {
                    internal uint Lo32;
                    internal uint Mid32;
                }
            }
        }
    }
}