// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable CS1591, CS1573, CS0465, CS0649, CS8019, CS1570, CS1584, CS1658
namespace Windows.Win32
{
    using global::System;
    using global::System.Diagnostics;
    using global::System.Runtime.CompilerServices;
    using global::System.Runtime.InteropServices;
    using win32 = global::Windows.Win32;

    namespace System.SystemServices
    {
        [Flags]
        internal enum PURGE_COMM_FLAGS : uint
        {
            PURGE_RXABORT = 0x00000002,
            PURGE_RXCLEAR = 0x00000008,
            PURGE_TXABORT = 0x00000001,
            PURGE_TXCLEAR = 0x00000004,
        }
    }
}