// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable CS1591, CS1573, CS0465, CS0649, CS8019, CS1570, CS1584, CS1658
namespace Windows.Win32
{
    using global::System;
    using global::System.Diagnostics;
    using global::System.Runtime.CompilerServices;
    using global::System.Runtime.InteropServices;
    using win32 = global::Windows.Win32;

    namespace UI.WindowsAndMessaging
    {
        /// <summary>Defines the dimensions and style of a dialog box.</summary>
        /// <remarks>
        /// <para>In a standard template for a dialog box, the <b>DLGTEMPLATE</b> structure is always immediately followed by three variable-length arrays that specify the menu, class, and title for the dialog box. When the DS_SETFONT style is specified, these arrays are also followed by a 16-bit value specifying point size and another variable-length array specifying a typeface name. Each array consists of one or more 16-bit elements. The menu, class, title, and font arrays must be aligned on <b>WORD</b> boundaries.</para>
        /// <para>Immediately following the <b>DLGTEMPLATE</b> structure is a menu array that identifies a menu resource for the dialog box. If the first element of this array is 0x0000, the dialog box has no menu and the array has no other elements. If the first element is 0xFFFF, the array has one additional element that specifies the ordinal value of a menu resource in an executable file. If the first element has any other value, the system treats the array as a null-terminated Unicode string that specifies the name of a menu resource in an executable file.</para>
        /// <para>Following the menu array is a class array that identifies the window class of the dialog box. If the first element of the array is 0x0000, the system uses the predefined dialog box class for the dialog box and the array has no other elements. If the first element is 0xFFFF, the array has one additional element that specifies the ordinal value of a predefined system window class. If the first element has any other value, the system treats the array as a null-terminated Unicode string that specifies the name of a registered window class.</para>
        /// <para>Following the class array is a title array that specifies a null-terminated Unicode string that contains the title of the dialog box. If the first element of this array is 0x0000, the dialog box has no title and the array has no other elements.</para>
        /// <para>The 16-bit point size value and the typeface array follow the title array, but only if the <b>style</b> member specifies the DS_SETFONT style. The point size value specifies the point size of the font to use for the text in the dialog box and its controls. The typeface array is a null-terminated Unicode string specifying the name of the typeface for the font. When these values are specified, the system creates a font having the specified size and typeface (if possible) and sends a <a href = "https://docs.microsoft.com/windows/desktop/winmsg/wm-setfont">WM_SETFONT</a> message to the dialog box procedure and the control window procedures as it creates the dialog box and controls.</para>
        /// <para>Following the <b>DLGTEMPLATE</b> header in a standard dialog box template are one or more <a href = "https://docs.microsoft.com/windows/desktop/api/winuser/ns-winuser-dlgitemtemplate">DLGITEMTEMPLATE</a> structures that define the dimensions and style of the controls in the dialog box. The <b>cdit</b> member specifies the number of <b>DLGITEMTEMPLATE</b> structures in the template. These <b>DLGITEMTEMPLATE</b> structures must be aligned on <b>DWORD</b> boundaries.</para>
        /// <para>If you specify character strings in the menu, class, title, or typeface arrays, you must use Unicode strings.</para>
        /// <para>The <b>x</b>, <b>y</b>, <b>cx</b>, and <b>cy</b> members specify values in dialog box units. You can convert these values to screen units (pixels) by using the <a href = "https://docs.microsoft.com/windows/desktop/api/winuser/nf-winuser-mapdialogrect">MapDialogRect</a> function.</para>
        /// <para><see href = "https://docs.microsoft.com/windows/win32/api//winuser/ns-winuser-dlgtemplate#">Read more on docs.microsoft.com</see>.</para>
        /// </remarks>
        [StructLayout(LayoutKind.Sequential, Pack = 2)]
        internal partial struct DLGTEMPLATE
        {
            /// <summary>
            /// <para>Type: <b>DWORD</b></para>
            /// <para>The style of the dialog box. This member can be a combination of <a href = "https://docs.microsoft.com/windows/desktop/winmsg/window-styles">window style values</a> (such as <b>WS_CAPTION</b> and <b>WS_SYSMENU</b>) and <a href = "https://docs.microsoft.com/windows/desktop/dlgbox/dialog-box-styles">dialog box style values</a> (such as <b>DS_CENTER</b>).</para>
            /// <para>If the style member includes the <b>DS_SETFONT</b> style, the header of the dialog box template contains additional data specifying the font to use for text in the client area and controls of the dialog box. The font data begins on the <b>WORD</b> boundary that follows the title array. The font data specifies a 16-bit point size value and a Unicode font name string. If possible, the system creates a font according to the specified values. Then the system sends a <a href = "https://docs.microsoft.com/windows/desktop/winmsg/wm-setfont">WM_SETFONT</a> message to the dialog box and to each control to provide a handle to the font. If <b>DS_SETFONT</b> is not specified, the dialog box template does not include the font data.</para>
            /// <para>The <b>DS_SHELLFONT</b> style is not supported in the <b>DLGTEMPLATE</b> header.</para>
            /// <para><see href = "https://docs.microsoft.com/windows/win32/api//winuser/ns-winuser-dlgtemplate#members">Read more on docs.microsoft.com</see>.</para>
            /// </summary>
            internal uint style;
            /// <summary>
            /// <para>Type: <b>DWORD</b></para>
            /// <para>The extended styles for a window. This member is not used to create dialog boxes, but applications that use dialog box templates can use it to create other types of windows. For a list of values, see <a href = "https://docs.microsoft.com/windows/desktop/winmsg/extended-window-styles">Extended Window Styles</a>.</para>
            /// <para><see href = "https://docs.microsoft.com/windows/win32/api//winuser/ns-winuser-dlgtemplate#members">Read more on docs.microsoft.com</see>.</para>
            /// </summary>
            internal uint dwExtendedStyle;
            /// <summary>
            /// <para>Type: <b>WORD</b></para>
            /// <para>The number of items in the dialog box.</para>
            /// <para><see href = "https://docs.microsoft.com/windows/win32/api//winuser/ns-winuser-dlgtemplate#members">Read more on docs.microsoft.com</see>.</para>
            /// </summary>
            internal ushort cdit;
            /// <summary>
            /// <para>Type: <b>short</b></para>
            /// <para>The x-coordinate, in dialog box units, of the upper-left corner of the dialog box.</para>
            /// <para><see href = "https://docs.microsoft.com/windows/win32/api//winuser/ns-winuser-dlgtemplate#members">Read more on docs.microsoft.com</see>.</para>
            /// </summary>
            internal short x;
            /// <summary>
            /// <para>Type: <b>short</b></para>
            /// <para>The y-coordinate, in dialog box units, of the upper-left corner of the dialog box.</para>
            /// <para><see href = "https://docs.microsoft.com/windows/win32/api//winuser/ns-winuser-dlgtemplate#members">Read more on docs.microsoft.com</see>.</para>
            /// </summary>
            internal short y;
            /// <summary>
            /// <para>Type: <b>short</b></para>
            /// <para>The width, in dialog box units, of the dialog box.</para>
            /// <para><see href = "https://docs.microsoft.com/windows/win32/api//winuser/ns-winuser-dlgtemplate#members">Read more on docs.microsoft.com</see>.</para>
            /// </summary>
            internal short cx;
            /// <summary>
            /// <para>Type: <b>short</b></para>
            /// <para>The height, in dialog box units, of the dialog box.</para>
            /// <para><see href = "https://docs.microsoft.com/windows/win32/api//winuser/ns-winuser-dlgtemplate#members">Read more on docs.microsoft.com</see>.</para>
            /// </summary>
            internal short cy;
        }
    }
}