// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable CS1591, CS1573, CS0465, CS0649, CS8019, CS1570, CS1584, CS1658
namespace Windows.Win32
{
    using global::System;
    using global::System.Diagnostics;
    using global::System.Runtime.CompilerServices;
    using global::System.Runtime.InteropServices;
    using win32 = global::Windows.Win32;

    namespace UI.WindowsAndMessaging
    {
        /// <summary>Contains the error message or message box display text for a message table resource.</summary>
        /// <remarks>
        /// <para><see href = "https://docs.microsoft.com/windows/win32/api//winnt/ns-winnt-message_resource_entry">Learn more about this API from docs.microsoft.com</see>.</para>
        /// </remarks>
        internal partial struct MESSAGE_RESOURCE_ENTRY
        {
            /// <summary>
            /// <para>Type: <b>WORD</b></para>
            /// <para>The length, in bytes, of the <b>MESSAGE_RESOURCE_ENTRY</b> structure.</para>
            /// <para><see href = "https://docs.microsoft.com/windows/win32/api//winnt/ns-winnt-message_resource_entry#members">Read more on docs.microsoft.com</see>.</para>
            /// </summary>
            internal ushort Length;
            /// <summary>
            /// <para>Type: <b>WORD</b></para>
            /// <para>Indicates that the string is encoded in Unicode, if equal to the value 0x0001. Indicates that the string is encoded in ANSI, if equal to the value 0x0000.</para>
            /// <para><see href = "https://docs.microsoft.com/windows/win32/api//winnt/ns-winnt-message_resource_entry#members">Read more on docs.microsoft.com</see>.</para>
            /// </summary>
            internal ushort Flags;
            /// <summary>
            /// <para>Type: <b>BYTE[1]</b></para>
            /// <para>Pointer to an array that contains the error message or message box display text.</para>
            /// <para><see href = "https://docs.microsoft.com/windows/win32/api//winnt/ns-winnt-message_resource_entry#members">Read more on docs.microsoft.com</see>.</para>
            /// </summary>
            internal __byte_1 Text;
            internal struct __byte_1
            {
                internal byte _0;
                /// <summary>Always <c>1</c>.</summary>
                internal int Length => 1;
            }
        }
    }
}