// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable CS1591, CS1573, CS0465, CS0649, CS8019, CS1570, CS1584, CS1658
namespace Windows.Win32
{
    using global::System;
    using global::System.Diagnostics;
    using global::System.Runtime.CompilerServices;
    using global::System.Runtime.InteropServices;
    using win32 = global::Windows.Win32;

    namespace UI.WindowsAndMessaging
    {
        internal enum VS_FIXEDFILEINFO_FILE_OS
        {
            VOS_DOS = 65536,
            VOS_NT = 262144,
            VOS__WINDOWS16 = 1,
            VOS__WINDOWS32 = 4,
            VOS_OS216 = 131072,
            VOS_OS232 = 196608,
            VOS__PM16 = 2,
            VOS__PM32 = 3,
            VOS_UNKNOWN = 0,
        }
    }
}