// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable CS1591, CS1573, CS0465, CS0649, CS8019, CS1570, CS1584, CS1658
namespace Windows.Win32
{
    using global::System;
    using global::System.Diagnostics;
    using global::System.Runtime.CompilerServices;
    using global::System.Runtime.InteropServices;
    using win32 = global::Windows.Win32;

    namespace Graphics.Gdi
    {
        /// <summary>The PAINTSTRUCT structure contains information for an application. This information can be used to paint the client area of a window owned by that application.</summary>
        /// <remarks>
        /// <para><see href = "https://docs.microsoft.com/windows/win32/api//winuser/ns-winuser-paintstruct">Learn more about this API from docs.microsoft.com</see>.</para>
        /// </remarks>
        internal partial struct PAINTSTRUCT
        {
            /// <summary>A handle to the display DC to be used for painting.</summary>
            internal win32.Graphics.Gdi.HDC hdc;
            /// <summary>Indicates whether the background must be erased. This value is nonzero if the application should erase the background. The application is responsible for erasing the background if a window class is created without a background brush. For more information, see the description of the <b>hbrBackground</b> member of the <a href = "https://docs.microsoft.com/windows/desktop/api/winuser/ns-winuser-wndclassa">WNDCLASS</a> structure.</summary>
            internal win32.System.SystemServices.BOOL fErase;
            /// <summary>A <a href = "https://docs.microsoft.com/windows/desktop/api/windef/ns-windef-rect">RECT</a> structure that specifies the upper left and lower right corners of the rectangle in which the painting is requested, in device units relative to the upper-left corner of the client area.</summary>
            internal win32.UI.DisplayDevices.RECT rcPaint;
            /// <summary>Reserved; used internally by the system.</summary>
            internal win32.System.SystemServices.BOOL fRestore;
            /// <summary>Reserved; used internally by the system.</summary>
            internal win32.System.SystemServices.BOOL fIncUpdate;
            /// <summary>Reserved; used internally by the system.</summary>
            internal __byte_32 rgbReserved;
            internal struct __byte_32
            {
                internal byte _0, _1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12, _13, _14, _15, _16, _17, _18, _19, _20, _21, _22, _23, _24, _25, _26, _27, _28, _29, _30, _31;
                /// <summary>Always <c>32</c>.</summary>
                internal int Length => 32;
            }
        }
    }
}