// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable CS1591, CS1573, CS0465, CS0649, CS8019, CS1570, CS1584, CS1658
namespace Windows.Win32
{
    using global::System;
    using global::System.Diagnostics;
    using global::System.Runtime.CompilerServices;
    using global::System.Runtime.InteropServices;
    using win32 = global::Windows.Win32;

    namespace System.Diagnostics.ProcessSnapshotting
    {
        /// <summary>Flags that specify what PssCaptureSnapshot captures.</summary>
        /// <remarks>
        /// <para>If both <b>PSS_CREATE_FORCE_BREAKAWAY</b> and <b>PSS_CREATE_BREAKAWAY</b> are specified, then <b>PSS_CREATE_FORCE_BREAKAWAY</b> takes precedence.</para>
        /// <para><see href = "https://docs.microsoft.com/windows/win32/api//processsnapshot/ne-processsnapshot-pss_capture_flags#">Read more on docs.microsoft.com</see>.</para>
        /// </remarks>
        [Flags]
        internal enum PSS_CAPTURE_FLAGS : uint
        {
            /// <summary>Capture nothing.</summary>
            PSS_CAPTURE_NONE = 0x00000000,
            /// <summary>Capture a snapshot of all cloneable pages in the process. The clone includes all <b>MEM_PRIVATE</b> regions, as well as all sections (<b>MEM_MAPPED</b> and <b>MEM_IMAGE</b>) that are shareable. All Win32 sections created via <a href = "https://docs.microsoft.com/windows/desktop/api/winbase/nf-winbase-createfilemappinga">CreateFileMapping</a> are shareable.</summary>
            PSS_CAPTURE_VA_CLONE = 0x00000001,
            /// <summary>(Do not use.)</summary>
            PSS_CAPTURE_RESERVED_00000002 = 0x00000002,
            /// <summary>Capture the handle table (handle values only).</summary>
            PSS_CAPTURE_HANDLES = 0x00000004,
            /// <summary>Capture name information for each handle.</summary>
            PSS_CAPTURE_HANDLE_NAME_INFORMATION = 0x00000008,
            /// <summary>Capture basic handle information such as <b>HandleCount</b>, <b>PointerCount</b>, <b>GrantedAccess</b>, etc.</summary>
            PSS_CAPTURE_HANDLE_BASIC_INFORMATION = 0x00000010,
            /// <summary>Capture type-specific information for supported object types: <b>Process</b>, <b>Thread</b>, <b>Event</b>, <b>Mutant</b>, <b>Section.</b></summary>
            PSS_CAPTURE_HANDLE_TYPE_SPECIFIC_INFORMATION = 0x00000020,
            /// <summary>Capture the handle tracing table.</summary>
            PSS_CAPTURE_HANDLE_TRACE = 0x00000040,
            /// <summary>Capture thread information (IDs only).</summary>
            PSS_CAPTURE_THREADS = 0x00000080,
            /// <summary>Capture the context for each thread.</summary>
            PSS_CAPTURE_THREAD_CONTEXT = 0x00000100,
            /// <summary>Capture extended context for each thread (e.g. <b>CONTEXT_XSTATE</b>).</summary>
            PSS_CAPTURE_THREAD_CONTEXT_EXTENDED = 0x00000200,
            /// <summary>(Do not use.)</summary>
            PSS_CAPTURE_RESERVED_00000400 = 0x00000400,
            /// <summary>Capture a snapshot of the virtual address space. The VA space is captured as an array of <a href = "https://docs.microsoft.com/windows/desktop/api/winnt/ns-winnt-memory_basic_information">MEMORY_BASIC_INFORMATION</a> structures. This flag does not capture the contents of the pages.</summary>
            PSS_CAPTURE_VA_SPACE = 0x00000800,
            /// <summary>
            /// <para>For <b>MEM_IMAGE</b> and <b>MEM_MAPPED</b> regions, dumps the path to the file backing the sections (identical to what <a href = "https://docs.microsoft.com/windows/desktop/api/psapi/nf-psapi-getmappedfilenamea">GetMappedFileName</a> returns). For <b>MEM_IMAGE</b> regions, also dumps:</para>
            /// <para></para>
            /// <para>This doc was truncated.</para>
            /// <para><see href = "https://docs.microsoft.com/windows/win32/api//processsnapshot/ne-processsnapshot-pss_capture_flags#members">Read more on docs.microsoft.com</see>.</para>
            /// </summary>
            PSS_CAPTURE_VA_SPACE_SECTION_INFORMATION = 0x00001000,
            /// <summary></summary>
            PSS_CAPTURE_IPT_TRACE = 0x00002000,
            PSS_CAPTURE_RESERVED_00004000 = 0x00004000,
            /// <summary>The breakaway is optional. If the clone process fails to create as a breakaway, then it is created still inside the job. This flag must be specified in combination with either <b>PSS_CREATE_FORCE_BREAKAWAY</b> and/or <b>PSS_CREATE_BREAKAWAY</b>.</summary>
            PSS_CREATE_BREAKAWAY_OPTIONAL = 0x04000000,
            /// <summary>The clone is broken away from the parent process' job. This is equivalent to <a href = "https://docs.microsoft.com/windows/desktop/api/processthreadsapi/nf-processthreadsapi-createprocessa">CreateProcess</a> flag <b>CREATE_BREAKAWAY_FROM_JOB</b>.</summary>
            PSS_CREATE_BREAKAWAY = 0x08000000,
            /// <summary>The clone is forcefully broken away the parent process's job. This is only allowed for Tcb-privileged callers.</summary>
            PSS_CREATE_FORCE_BREAKAWAY = 0x10000000,
            /// <summary>The facility should not use the process heap for any persistent or transient allocations. The use of the heap may be undesirable in certain contexts such as creation of snapshots in the exception reporting path (where the heap may be corrupted).</summary>
            PSS_CREATE_USE_VM_ALLOCATIONS = 0x20000000,
            /// <summary>Measure performance of the facility. Performance counters can be retrieved via <a href = "https://docs.microsoft.com/previous-versions/windows/desktop/api/processsnapshot/nf-processsnapshot-pssquerysnapshot">PssQuerySnapshot</a> with the <b>PSS_QUERY_PERFORMANCE_COUNTERS</b> information class of <a href = "https://docs.microsoft.com/previous-versions/windows/desktop/api/processsnapshot/ne-processsnapshot-pss_query_information_class">PSS_QUERY_INFORMATION_CLASS</a>.</summary>
            PSS_CREATE_MEASURE_PERFORMANCE = 0x40000000,
            /// <summary>
            /// <para>The virtual address (VA) clone process does not hold a reference to the underlying image. This will cause functions such as <a href = "https://docs.microsoft.com/windows/desktop/api/winbase/nf-winbase-queryfullprocessimagenamea">QueryFullProcessImageName</a> to fail on the VA clone process.</para>
            /// <para><div class = "alert"><b>Important</b>  <p class = "note"> This flag has no effect unless <b>PSS_CAPTURE_VA_CLONE</b> is specified.</para>
            /// <para></div> <div> </div></para>
            /// <para><see href = "https://docs.microsoft.com/windows/win32/api//processsnapshot/ne-processsnapshot-pss_capture_flags#members">Read more on docs.microsoft.com</see>.</para>
            /// </summary>
            PSS_CREATE_RELEASE_SECTION = 0x80000000,
        }
    }
}