// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable CS1591, CS1573, CS0465, CS0649, CS8019, CS1570, CS1584, CS1658
namespace Windows.Win32
{
    using global::System;
    using global::System.Diagnostics;
    using global::System.Runtime.CompilerServices;
    using global::System.Runtime.InteropServices;
    using win32 = global::Windows.Win32;

    namespace Graphics.Direct3D11
    {
        /// <summary>Specifies if the hardware and driver support conservative rasterization and at what tier level.</summary>
        /// <remarks>
        /// <para><see href = "https://docs.microsoft.com/windows/win32/api//d3d11/ne-d3d11-d3d11_conservative_rasterization_tier">Learn more about this API from docs.microsoft.com</see>.</para>
        /// </remarks>
        internal enum D3D11_CONSERVATIVE_RASTERIZATION_TIER
        {
            /// <summary>Conservative rasterization isn't supported.</summary>
            D3D11_CONSERVATIVE_RASTERIZATION_NOT_SUPPORTED = 0,
            /// <summary>Tier_1 conservative rasterization is supported.</summary>
            D3D11_CONSERVATIVE_RASTERIZATION_TIER_1 = 1,
            /// <summary>Tier_2 conservative rasterization is supported.</summary>
            D3D11_CONSERVATIVE_RASTERIZATION_TIER_2 = 2,
            /// <summary>Tier_3 conservative rasterization is supported.</summary>
            D3D11_CONSERVATIVE_RASTERIZATION_TIER_3 = 3,
        }
    }
}