// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable CS1591, CS1573, CS0465, CS0649, CS8019, CS1570, CS1584, CS1658
namespace Windows.Win32
{
    using global::System;
    using global::System.Diagnostics;
    using global::System.Runtime.CompilerServices;
    using global::System.Runtime.InteropServices;
    using win32 = global::Windows.Win32;

    namespace Graphics.Direct3D11
    {
        /// <summary>Specifies interpolation mode, which affects how values are calculated during rasterization.</summary>
        /// <remarks>
        /// <para><see href = "https://docs.microsoft.com/windows/win32/api//d3dcommon/ne-d3dcommon-d3d_interpolation_mode">Learn more about this API from docs.microsoft.com</see>.</para>
        /// </remarks>
        internal enum D3D_INTERPOLATION_MODE
        {
            /// <summary>The interpolation mode is undefined.</summary>
            D3D_INTERPOLATION_UNDEFINED = 0,
            /// <summary>Don't interpolate between register values.</summary>
            D3D_INTERPOLATION_CONSTANT = 1,
            /// <summary>Interpolate linearly between register values.</summary>
            D3D_INTERPOLATION_LINEAR = 2,
            /// <summary>Interpolate linearly between register values but centroid clamped when multisampling.</summary>
            D3D_INTERPOLATION_LINEAR_CENTROID = 3,
            /// <summary>Interpolate linearly between register values but with no perspective correction.</summary>
            D3D_INTERPOLATION_LINEAR_NOPERSPECTIVE = 4,
            /// <summary>Interpolate linearly between register values but with no perspective correction and centroid clamped when multisampling.</summary>
            D3D_INTERPOLATION_LINEAR_NOPERSPECTIVE_CENTROID = 5,
            /// <summary>Interpolate linearly between register values but sample clamped when multisampling.</summary>
            D3D_INTERPOLATION_LINEAR_SAMPLE = 6,
            /// <summary>Interpolate linearly between register values but with no perspective correction and sample clamped when multisampling.</summary>
            D3D_INTERPOLATION_LINEAR_NOPERSPECTIVE_SAMPLE = 7,
        }
    }
}