// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable CS1591, CS1573, CS0465, CS0649, CS8019, CS1570, CS1584, CS1658
namespace Windows.Win32
{
    using global::System;
    using global::System.Diagnostics;
    using global::System.Runtime.CompilerServices;
    using global::System.Runtime.InteropServices;
    using win32 = global::Windows.Win32;

    namespace Graphics.Direct3D11
    {
        [Guid("54384F1B-5B3E-4BB7-AE01-60BA3097CBB6")]
        internal unsafe struct ID3D11LibraryReflection
        {
            /// <inheritdoc cref = "QueryInterface(global::System.Guid*, void **)"/>
            internal unsafe win32.System.Com.HRESULT QueryInterface(in global::System.Guid riid, out void *ppvObject)
            {
                fixed (void **ppvObjectLocal = &ppvObject)
                {
                    fixed (global::System.Guid*riidLocal = &riid)
                    {
                        win32.System.Com.HRESULT __result = this.QueryInterface(riidLocal, ppvObjectLocal);
                        return __result;
                    }
                }
            }

            internal unsafe win32.System.Com.HRESULT QueryInterface(global::System.Guid*riid, void **ppvObject)
            {
                fixed (ID3D11LibraryReflection*pThis = &this)
                    return lpVtbl->QueryInterface_1(pThis, riid, ppvObject);
            }

            internal uint AddRef()
            {
                fixed (ID3D11LibraryReflection*pThis = &this)
                    return lpVtbl->AddRef_2(pThis);
            }

            internal uint Release()
            {
                fixed (ID3D11LibraryReflection*pThis = &this)
                    return lpVtbl->Release_3(pThis);
            }

            /// <inheritdoc cref = "GetDesc(win32.Graphics.Direct3D11.D3D11_LIBRARY_DESC*)"/>
            internal unsafe win32.System.Com.HRESULT GetDesc(out win32.Graphics.Direct3D11.D3D11_LIBRARY_DESC pDesc)
            {
                fixed (win32.Graphics.Direct3D11.D3D11_LIBRARY_DESC*pDescLocal = &pDesc)
                {
                    win32.System.Com.HRESULT __result = this.GetDesc(pDescLocal);
                    return __result;
                }
            }

            /// <summary>Fills the library descriptor structure for the library reflection.</summary>
            /// <param name = "pDesc">
            /// <para>Type: <b><a href = "https://docs.microsoft.com/windows/desktop/api/d3d11shader/ns-d3d11shader-d3d11_library_desc">D3D11_LIBRARY_DESC</a>*</b></para>
            /// <para>A pointer to a <a href = "https://docs.microsoft.com/windows/desktop/api/d3d11shader/ns-d3d11shader-d3d11_library_desc">D3D11_LIBRARY_DESC</a> structure that receives a description of the library reflection.</para>
            /// <para><see href = "https://docs.microsoft.com/windows/win32/api//d3d11shader/nf-d3d11shader-id3d11libraryreflection-getdesc#parameters">Read more on docs.microsoft.com</see>.</para>
            /// </param>
            /// <returns>
            /// <para>Type: <b><a href = "/windows/win32/com/structure-of-com-error-codes">HRESULT</a></b></para>
            /// <para>Returns one of the <a href = "/windows/desktop/direct3d11/d3d11-graphics-reference-returnvalues">Direct3D 11 Return Codes</a>.</para>
            /// </returns>
            /// <remarks>
            /// <para><see href = "https://docs.microsoft.com/windows/win32/api//d3d11shader/nf-d3d11shader-id3d11libraryreflection-getdesc">Learn more about this API from docs.microsoft.com</see>.</para>
            /// </remarks>
            internal unsafe win32.System.Com.HRESULT GetDesc(win32.Graphics.Direct3D11.D3D11_LIBRARY_DESC*pDesc)
            {
                fixed (ID3D11LibraryReflection*pThis = &this)
                    return lpVtbl->GetDesc_4(pThis, pDesc);
            }

            /// <summary>Gets the function reflector.</summary>
            /// <param name = "FunctionIndex">
            /// <para>Type: <b>INT</b></para>
            /// <para>The zero-based index of the function reflector to retrieve.</para>
            /// <para><see href = "https://docs.microsoft.com/windows/win32/api//d3d11shader/nf-d3d11shader-id3d11libraryreflection-getfunctionbyindex#parameters">Read more on docs.microsoft.com</see>.</para>
            /// </param>
            /// <returns>
            /// <para>Type: <b><a href = "/windows/desktop/api/d3d11shader/nn-d3d11shader-id3d11functionreflection">ID3D11FunctionReflection</a>*</b></para>
            /// <para>A pointer to a <a href = "/windows/desktop/api/d3d11shader/nn-d3d11shader-id3d11functionreflection">ID3D11FunctionReflection</a> interface that represents the function reflector.</para>
            /// </returns>
            /// <remarks>
            /// <para><see href = "https://docs.microsoft.com/windows/win32/api//d3d11shader/nf-d3d11shader-id3d11libraryreflection-getfunctionbyindex">Learn more about this API from docs.microsoft.com</see>.</para>
            /// </remarks>
            internal unsafe win32.Graphics.Direct3D11.ID3D11FunctionReflection*GetFunctionByIndex(int FunctionIndex)
            {
                fixed (ID3D11LibraryReflection*pThis = &this)
                    return lpVtbl->GetFunctionByIndex_5(pThis, FunctionIndex);
            }

            private struct Vtbl
            {
                internal delegate *unmanaged[Stdcall]<ID3D11LibraryReflection*, global::System.Guid*, void **, win32.System.Com.HRESULT>QueryInterface_1;
                internal delegate *unmanaged[Stdcall]<ID3D11LibraryReflection*, uint>AddRef_2;
                internal delegate *unmanaged[Stdcall]<ID3D11LibraryReflection*, uint>Release_3;
                internal delegate *unmanaged[Stdcall]<ID3D11LibraryReflection*, win32.Graphics.Direct3D11.D3D11_LIBRARY_DESC*, win32.System.Com.HRESULT>GetDesc_4;
                internal delegate *unmanaged[Stdcall]<ID3D11LibraryReflection*, int, win32.Graphics.Direct3D11.ID3D11FunctionReflection*>GetFunctionByIndex_5;
            }

            private Vtbl*lpVtbl;
        }
    }
}