// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable CS1591, CS1573, CS0465, CS0649, CS8019, CS1570, CS1584, CS1658
namespace Windows.Win32
{
    using global::System;
    using global::System.Diagnostics;
    using global::System.Runtime.CompilerServices;
    using global::System.Runtime.InteropServices;
    using win32 = global::Windows.Win32;

    namespace System.WindowsProgramming
    {
        internal enum STD_HANDLE_TYPE : uint
        {
            STD_INPUT_HANDLE = 4294967286U,
            STD_OUTPUT_HANDLE = 4294967285U,
            STD_ERROR_HANDLE = 4294967284U,
        }
    }
}