// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable CS1591, CS1573, CS0465, CS0649, CS8019, CS1570, CS1584, CS1658
namespace Windows.Win32
{
    using global::System;
    using global::System.Diagnostics;
    using global::System.Runtime.CompilerServices;
    using global::System.Runtime.InteropServices;
    using win32 = global::Windows.Win32;

    namespace Graphics.Direct2D
    {
        /// <summary>Contains the dimensions and corner radii of a rounded rectangle.</summary>
        /// <remarks>
        /// <para>Each corner of the rectangle specified by the <i>rect</i> is replaced with a quarter ellipse, with a radius in each direction specified by <i>radiusX</i> and <i>radiusY</i>.</para>
        /// <para>If the <i>radiusX</i> is greater than or equal to half the width of the rectangle, and the <i>radiusY</i> is greater than or equal to one-half the height, the rounded rectangle is an ellipse with the same width and height of the <i>rect</i>.</para>
        /// <para>Even when both <i>radiuX</i> and <i>radiusY</i> are zero, the rounded rectangle is different from a rectangle., When stroked, the corners of the rounded rectangle are roundly joined, not mitered (square).</para>
        /// <para><see href = "https://docs.microsoft.com/windows/win32/api//d2d1/ns-d2d1-d2d1_rounded_rect#">Read more on docs.microsoft.com</see>.</para>
        /// </remarks>
        internal partial struct D2D1_ROUNDED_RECT
        {
            /// <summary>
            /// <para>Type: <b><a href = "https://docs.microsoft.com/windows/win32/Direct2D/d2d1-rect-f">D2D1_RECT_F</a></b></para>
            /// <para>The coordinates of the rectangle.</para>
            /// <para><see href = "https://docs.microsoft.com/windows/win32/api//d2d1/ns-d2d1-d2d1_rounded_rect#members">Read more on docs.microsoft.com</see>.</para>
            /// </summary>
            internal win32.Graphics.Direct2D.D2D_RECT_F rect;
            /// <summary>
            /// <para>Type: <b>FLOAT</b></para>
            /// <para>The x-radius for the quarter ellipse that is drawn to replace every corner of the rectangle.</para>
            /// <para><see href = "https://docs.microsoft.com/windows/win32/api//d2d1/ns-d2d1-d2d1_rounded_rect#members">Read more on docs.microsoft.com</see>.</para>
            /// </summary>
            internal float radiusX;
            /// <summary>
            /// <para>Type: <b>FLOAT</b></para>
            /// <para>The y-radius for the quarter ellipse that is drawn to replace every corner of the rectangle.</para>
            /// <para><see href = "https://docs.microsoft.com/windows/win32/api//d2d1/ns-d2d1-d2d1_rounded_rect#members">Read more on docs.microsoft.com</see>.</para>
            /// </summary>
            internal float radiusY;
        }
    }
}