// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable CS1591, CS1573, CS0465, CS0649, CS8019, CS1570, CS1584, CS1658
namespace Windows.Win32
{
    using global::System;
    using global::System.Diagnostics;
    using global::System.Runtime.CompilerServices;
    using global::System.Runtime.InteropServices;
    using win32 = global::Windows.Win32;

    namespace Graphics.Direct2D
    {
        /// <summary>Represents filtering modes that a transform may select to use on input textures.</summary>
        /// <remarks>
        /// <para>This enumeration has the same numeric values as <a href = "https://docs.microsoft.com/windows/desktop/api/d3d11/ne-d3d11-d3d11_filter">D3D11_FILTER</a>.</para>
        /// <para><see href = "https://docs.microsoft.com/windows/win32/api//d2d1effectauthor/ne-d2d1effectauthor-d2d1_filter#">Read more on docs.microsoft.com</see>.</para>
        /// </remarks>
        internal enum D2D1_FILTER : uint
        {
            /// <summary>Use point sampling for minification, magnification, and mip-level sampling.</summary>
            D2D1_FILTER_MIN_MAG_MIP_POINT = 0U,
            /// <summary>Use point sampling for minification and magnification; use linear interpolation for mip-level sampling.</summary>
            D2D1_FILTER_MIN_MAG_POINT_MIP_LINEAR = 1U,
            /// <summary>Use point sampling for minification; use linear interpolation for magnification; use point sampling for mip-level sampling.</summary>
            D2D1_FILTER_MIN_POINT_MAG_LINEAR_MIP_POINT = 4U,
            /// <summary>Use point sampling for minification; use linear interpolation for magnification and mip-level sampling.</summary>
            D2D1_FILTER_MIN_POINT_MAG_MIP_LINEAR = 5U,
            /// <summary>Use linear interpolation for minification; use point sampling for magnification and mip-level sampling.</summary>
            D2D1_FILTER_MIN_LINEAR_MAG_MIP_POINT = 16U,
            /// <summary>Use linear interpolation for minification; use point sampling for magnification; use linear interpolation for mip-level sampling.</summary>
            D2D1_FILTER_MIN_LINEAR_MAG_POINT_MIP_LINEAR = 17U,
            /// <summary>Use linear interpolation for minification and magnification; use point sampling for mip-level sampling.</summary>
            D2D1_FILTER_MIN_MAG_LINEAR_MIP_POINT = 20U,
            /// <summary>Use linear interpolation for minification, magnification, and mip-level sampling.</summary>
            D2D1_FILTER_MIN_MAG_MIP_LINEAR = 21U,
            /// <summary>Use anisotropic interpolation for minification, magnification, and mip-level sampling.</summary>
            D2D1_FILTER_ANISOTROPIC = 85U,
            /// <summary></summary>
            D2D1_FILTER_FORCE_DWORD = 4294967295U,
        }
    }
}