// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable CS1591, CS1573, CS0465, CS0649, CS8019, CS1570, CS1584, CS1658
namespace Windows.Win32
{
    using global::System;
    using global::System.Diagnostics;
    using global::System.Runtime.CompilerServices;
    using global::System.Runtime.InteropServices;
    using win32 = global::Windows.Win32;

    namespace Graphics.Direct2D
    {
        /// <summary>Indicates whether a specific ID2D1SimplifiedGeometrySink figure is filled or hollow.</summary>
        /// <remarks>
        /// <para><see href = "https://docs.microsoft.com/windows/win32/api//d2d1/ne-d2d1-d2d1_figure_begin">Learn more about this API from docs.microsoft.com</see>.</para>
        /// </remarks>
        internal enum D2D1_FIGURE_BEGIN : uint
        {
            /// <summary>
            /// <para>Indicates the figure will be filled by the FillGeometry (<a href = "https://docs.microsoft.com/windows/win32/api/d2d1_1/nf-d2d1_1-id2d1commandsink-fillgeometry">ID2D1CommandSink::FillGeometry</a> or <a href = "https://docs.microsoft.com/windows/win32/api/d2d1/nf-d2d1-id2d1rendertarget-fillgeometry">ID2D1RenderTarget::FillGeometry</a>) method.</para>
            /// <para><see href = "https://docs.microsoft.com/windows/win32/api//d2d1/ne-d2d1-d2d1_figure_begin#members">Read more on docs.microsoft.com</see>.</para>
            /// </summary>
            D2D1_FIGURE_BEGIN_FILLED = 0U,
            /// <summary>
            /// <para>Indicates the figure will not be filled by the FillGeometry (<a href = "https://docs.microsoft.com/windows/win32/api/d2d1_1/nf-d2d1_1-id2d1commandsink-fillgeometry">ID2D1CommandSink::FillGeometry</a> or <a href = "https://docs.microsoft.com/windows/win32/api/d2d1/nf-d2d1-id2d1rendertarget-fillgeometry">ID2D1RenderTarget::FillGeometry</a>) method and will only consist of an outline. Moreover, the bounds of a hollow figure are zero. D2D1_FIGURE_BEGIN_HOLLOW should be used for stroking, or for other geometry operations.</para>
            /// <para><see href = "https://docs.microsoft.com/windows/win32/api//d2d1/ne-d2d1-d2d1_figure_begin#members">Read more on docs.microsoft.com</see>.</para>
            /// </summary>
            D2D1_FIGURE_BEGIN_HOLLOW = 1U,
            /// <summary></summary>
            D2D1_FIGURE_BEGIN_FORCE_DWORD = 4294967295U,
        }
    }
}