// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable CS1591, CS1573, CS0465, CS0649, CS8019, CS1570, CS1584, CS1658
namespace Windows.Win32
{
    using global::System;
    using global::System.Diagnostics;
    using global::System.Runtime.CompilerServices;
    using global::System.Runtime.InteropServices;
    using win32 = global::Windows.Win32;

    namespace Graphics.Direct2D
    {
        /// <summary>Values for the D2D1_HIGHLIGHTSANDSHADOWS_PROP_INPUT_GAMMA property of the Highlights and Shadows effect.</summary>
        /// <remarks>
        /// <para><see href = "https://docs.microsoft.com/windows/win32/api//d2d1effects_2/ne-d2d1effects_2-d2d1_highlightsandshadows_input_gamma">Learn more about this API from docs.microsoft.com</see>.</para>
        /// </remarks>
        internal enum D2D1_HIGHLIGHTSANDSHADOWS_INPUT_GAMMA : uint
        {
            /// <summary>Indicates the input image is in linear gamma space.</summary>
            D2D1_HIGHLIGHTSANDSHADOWS_INPUT_GAMMA_LINEAR = 0U,
            /// <summary>Indicates the input image is sRGB gamma space.</summary>
            D2D1_HIGHLIGHTSANDSHADOWS_INPUT_GAMMA_SRGB = 1U,
            /// <summary></summary>
            D2D1_HIGHLIGHTSANDSHADOWS_INPUT_GAMMA_FORCE_DWORD = 4294967295U,
        }
    }
}