// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable CS1591, CS1573, CS0465, CS0649, CS8019, CS1570, CS1584, CS1658
namespace Windows.Win32
{
    using global::System;
    using global::System.Diagnostics;
    using global::System.Runtime.CompilerServices;
    using global::System.Runtime.InteropServices;
    using win32 = global::Windows.Win32;

    namespace Graphics.Direct2D
    {
        [Guid("28211A43-7D89-476F-8181-2D6159B220AD")]
        internal unsafe struct ID2D1Effect
        {
            /// <inheritdoc cref = "QueryInterface(global::System.Guid*, void **)"/>
            internal unsafe win32.System.Com.HRESULT QueryInterface(in global::System.Guid riid, out void *ppvObject)
            {
                fixed (void **ppvObjectLocal = &ppvObject)
                {
                    fixed (global::System.Guid*riidLocal = &riid)
                    {
                        win32.System.Com.HRESULT __result = this.QueryInterface(riidLocal, ppvObjectLocal);
                        return __result;
                    }
                }
            }

            internal unsafe win32.System.Com.HRESULT QueryInterface(global::System.Guid*riid, void **ppvObject)
            {
                fixed (ID2D1Effect*pThis = &this)
                    return lpVtbl->QueryInterface_1(pThis, riid, ppvObject);
            }

            internal uint AddRef()
            {
                fixed (ID2D1Effect*pThis = &this)
                    return lpVtbl->AddRef_2(pThis);
            }

            internal uint Release()
            {
                fixed (ID2D1Effect*pThis = &this)
                    return lpVtbl->Release_3(pThis);
            }

            internal uint GetPropertyCount()
            {
                fixed (ID2D1Effect*pThis = &this)
                    return lpVtbl->GetPropertyCount_4(pThis);
            }

            internal win32.System.Com.HRESULT GetPropertyName(uint index, win32.System.SystemServices.PWSTR name, uint nameCount)
            {
                fixed (ID2D1Effect*pThis = &this)
                    return lpVtbl->GetPropertyName_5(pThis, index, name, nameCount);
            }

            internal uint GetPropertyNameLength(uint index)
            {
                fixed (ID2D1Effect*pThis = &this)
                    return lpVtbl->GetPropertyNameLength_6(pThis, index);
            }

            internal win32.Graphics.Direct2D.D2D1_PROPERTY_TYPE GetType(uint index)
            {
                fixed (ID2D1Effect*pThis = &this)
                    return lpVtbl->GetType_7(pThis, index);
            }

            /// <inheritdoc cref = "GetPropertyIndex(win32.System.SystemServices.PCWSTR)"/>
            internal unsafe uint GetPropertyIndex(string name)
            {
                fixed (char *nameLocal = name)
                {
                    uint __result = this.GetPropertyIndex(nameLocal);
                    return __result;
                }
            }

            internal uint GetPropertyIndex(win32.System.SystemServices.PCWSTR name)
            {
                fixed (ID2D1Effect*pThis = &this)
                    return lpVtbl->GetPropertyIndex_8(pThis, name);
            }

            /// <inheritdoc cref = "SetValueByName(win32.System.SystemServices.PCWSTR, win32.Graphics.Direct2D.D2D1_PROPERTY_TYPE, byte *, uint)"/>
            internal unsafe win32.System.Com.HRESULT SetValueByName(string name, win32.Graphics.Direct2D.D2D1_PROPERTY_TYPE type, ReadOnlySpan<byte> data)
            {
                fixed (byte *dataLocal = data)
                {
                    fixed (char *nameLocal = name)
                    {
                        win32.System.Com.HRESULT __result = this.SetValueByName(nameLocal, type, dataLocal, (uint)data.Length);
                        return __result;
                    }
                }
            }

            internal unsafe win32.System.Com.HRESULT SetValueByName(win32.System.SystemServices.PCWSTR name, win32.Graphics.Direct2D.D2D1_PROPERTY_TYPE type, byte *data, uint dataSize)
            {
                fixed (ID2D1Effect*pThis = &this)
                    return lpVtbl->SetValueByName_9(pThis, name, type, data, dataSize);
            }

            /// <inheritdoc cref = "SetValue(uint, win32.Graphics.Direct2D.D2D1_PROPERTY_TYPE, byte *, uint)"/>
            internal unsafe win32.System.Com.HRESULT SetValue(uint index, win32.Graphics.Direct2D.D2D1_PROPERTY_TYPE type, ReadOnlySpan<byte> data)
            {
                fixed (byte *dataLocal = data)
                {
                    win32.System.Com.HRESULT __result = this.SetValue(index, type, dataLocal, (uint)data.Length);
                    return __result;
                }
            }

            internal unsafe win32.System.Com.HRESULT SetValue(uint index, win32.Graphics.Direct2D.D2D1_PROPERTY_TYPE type, byte *data, uint dataSize)
            {
                fixed (ID2D1Effect*pThis = &this)
                    return lpVtbl->SetValue_10(pThis, index, type, data, dataSize);
            }

            /// <inheritdoc cref = "GetValueByName(win32.System.SystemServices.PCWSTR, win32.Graphics.Direct2D.D2D1_PROPERTY_TYPE, byte *, uint)"/>
            internal unsafe win32.System.Com.HRESULT GetValueByName(string name, win32.Graphics.Direct2D.D2D1_PROPERTY_TYPE type, Span<byte> data)
            {
                fixed (byte *dataLocal = data)
                {
                    fixed (char *nameLocal = name)
                    {
                        win32.System.Com.HRESULT __result = this.GetValueByName(nameLocal, type, dataLocal, (uint)data.Length);
                        return __result;
                    }
                }
            }

            internal unsafe win32.System.Com.HRESULT GetValueByName(win32.System.SystemServices.PCWSTR name, win32.Graphics.Direct2D.D2D1_PROPERTY_TYPE type, byte *data, uint dataSize)
            {
                fixed (ID2D1Effect*pThis = &this)
                    return lpVtbl->GetValueByName_11(pThis, name, type, data, dataSize);
            }

            /// <inheritdoc cref = "GetValue(uint, win32.Graphics.Direct2D.D2D1_PROPERTY_TYPE, byte *, uint)"/>
            internal unsafe win32.System.Com.HRESULT GetValue(uint index, win32.Graphics.Direct2D.D2D1_PROPERTY_TYPE type, Span<byte> data)
            {
                fixed (byte *dataLocal = data)
                {
                    win32.System.Com.HRESULT __result = this.GetValue(index, type, dataLocal, (uint)data.Length);
                    return __result;
                }
            }

            internal unsafe win32.System.Com.HRESULT GetValue(uint index, win32.Graphics.Direct2D.D2D1_PROPERTY_TYPE type, byte *data, uint dataSize)
            {
                fixed (ID2D1Effect*pThis = &this)
                    return lpVtbl->GetValue_12(pThis, index, type, data, dataSize);
            }

            internal uint GetValueSize(uint index)
            {
                fixed (ID2D1Effect*pThis = &this)
                    return lpVtbl->GetValueSize_13(pThis, index);
            }

            internal unsafe win32.System.Com.HRESULT GetSubProperties(uint index, [Optional] win32.Graphics.Direct2D.ID2D1Properties**subProperties)
            {
                fixed (ID2D1Effect*pThis = &this)
                    return lpVtbl->GetSubProperties_14(pThis, index, subProperties);
            }

            /// <summary>Sets the given input image by index.</summary>
            /// <param name = "index">
            /// <para>Type: <b>UINT32</b></para>
            /// <para>The index of the image to set.</para>
            /// <para><see href = "https://docs.microsoft.com/windows/win32/api//d2d1_1/nf-d2d1_1-id2d1effect-setinput#parameters">Read more on docs.microsoft.com</see>.</para>
            /// </param>
            /// <param name = "input">
            /// <para>Type: <b><a href = "https://docs.microsoft.com/windows/desktop/api/d2d1/nn-d2d1-id2d1image">ID2D1Image</a>*</b></para>
            /// <para>The input image to set.</para>
            /// <para><see href = "https://docs.microsoft.com/windows/win32/api//d2d1_1/nf-d2d1_1-id2d1effect-setinput#parameters">Read more on docs.microsoft.com</see>.</para>
            /// </param>
            /// <param name = "invalidate">
            /// <para>Type: <b>BOOL</b></para>
            /// <para>Whether to invalidate the graph at the location of the effect input</para>
            /// <para><see href = "https://docs.microsoft.com/windows/win32/api//d2d1_1/nf-d2d1_1-id2d1effect-setinput#parameters">Read more on docs.microsoft.com</see>.</para>
            /// </param>
            /// <remarks>
            /// <para>If the input index is out of range, the input image is ignored.</para>
            /// <para><see href = "https://docs.microsoft.com/windows/win32/api//d2d1_1/nf-d2d1_1-id2d1effect-setinput#">Read more on docs.microsoft.com</see>.</para>
            /// </remarks>
            internal unsafe void SetInput(uint index, [Optional] win32.Graphics.Direct2D.ID2D1Image*input, win32.System.SystemServices.BOOL invalidate)
            {
                fixed (ID2D1Effect*pThis = &this)
                    lpVtbl->SetInput_15(pThis, index, input, invalidate);
            }

            /// <summary>Allows the application to change the number of inputs to an effect.</summary>
            /// <param name = "inputCount">
            /// <para>Type: <b>UINT32</b></para>
            /// <para>The number of inputs to the effect.</para>
            /// <para><see href = "https://docs.microsoft.com/windows/win32/api//d2d1_1/nf-d2d1_1-id2d1effect-setinputcount#parameters">Read more on docs.microsoft.com</see>.</para>
            /// </param>
            /// <returns>
            /// <para>Type: <b>HRESULT</b></para>
            /// <para>The method returns an <b>HRESULT</b>. Possible values include, but are not limited to, those in the following table.</para>
            /// <para></para>
            /// <para>This doc was truncated.</para>
            /// </returns>
            /// <remarks>
            /// <para><see href = "https://docs.microsoft.com/windows/win32/api//d2d1_1/nf-d2d1_1-id2d1effect-setinputcount">Learn more about this API from docs.microsoft.com</see>.</para>
            /// </remarks>
            internal win32.System.Com.HRESULT SetInputCount(uint inputCount)
            {
                fixed (ID2D1Effect*pThis = &this)
                    return lpVtbl->SetInputCount_16(pThis, inputCount);
            }

            /// <summary>Gets the given input image by index.</summary>
            /// <param name = "index">
            /// <para>Type: <b>UINT32</b></para>
            /// <para>The index of the image to retrieve.</para>
            /// <para><see href = "https://docs.microsoft.com/windows/win32/api//d2d1_1/nf-d2d1_1-id2d1effect-getinput#parameters">Read more on docs.microsoft.com</see>.</para>
            /// </param>
            /// <param name = "input">
            /// <para>Type: <b><a href = "https://docs.microsoft.com/windows/desktop/api/d2d1/nn-d2d1-id2d1image">ID2D1Image</a>**</b></para>
            /// <para>When this method returns, contains the address of a pointer to the image that is identified by <i>Index</i>.</para>
            /// <para><see href = "https://docs.microsoft.com/windows/win32/api//d2d1_1/nf-d2d1_1-id2d1effect-getinput#parameters">Read more on docs.microsoft.com</see>.</para>
            /// </param>
            /// <remarks>
            /// <para>If the input index is out of range, the returned image will be <b>NULL</b>.</para>
            /// <para><see href = "https://docs.microsoft.com/windows/win32/api//d2d1_1/nf-d2d1_1-id2d1effect-getinput#">Read more on docs.microsoft.com</see>.</para>
            /// </remarks>
            internal unsafe void GetInput(uint index, [Optional] win32.Graphics.Direct2D.ID2D1Image**input)
            {
                fixed (ID2D1Effect*pThis = &this)
                    lpVtbl->GetInput_17(pThis, index, input);
            }

            /// <summary>Gets the number of inputs to the effect.</summary>
            /// <returns>
            /// <para>Type: <b>UINT32</b></para>
            /// <para>This method returns the number of inputs to the effect.</para>
            /// </returns>
            /// <remarks>
            /// <para><see href = "https://docs.microsoft.com/windows/win32/api//d2d1_1/nf-d2d1_1-id2d1effect-getinputcount">Learn more about this API from docs.microsoft.com</see>.</para>
            /// </remarks>
            internal uint GetInputCount()
            {
                fixed (ID2D1Effect*pThis = &this)
                    return lpVtbl->GetInputCount_18(pThis);
            }

            /// <summary>Gets the output image from the effect.</summary>
            /// <param name = "outputImage">
            /// <para>Type: <b><a href = "https://docs.microsoft.com/windows/desktop/api/d2d1/nn-d2d1-id2d1image">ID2D1Image</a>**</b></para>
            /// <para>When this method returns, contains the address of a pointer to the output image for the effect.</para>
            /// <para><see href = "https://docs.microsoft.com/windows/win32/api//d2d1_1/nf-d2d1_1-id2d1effect-getoutput#parameters">Read more on docs.microsoft.com</see>.</para>
            /// </param>
            /// <remarks>
            /// <para>The output image  can be set as an input to another effect, or can be directly passed into the <a href = "https://docs.microsoft.com/windows/desktop/api/d2d1_1/nn-d2d1_1-id2d1devicecontext">ID2D1DeviceContext</a> in order to render the effect.</para>
            /// <para>It is  also possible to use <a href = "https://docs.microsoft.com/windows/desktop/api/unknwn/nf-unknwn-iunknown-queryinterface(q)">QueryInterface</a> to retrieve the same output image.</para>
            /// <para><see href = "https://docs.microsoft.com/windows/win32/api//d2d1_1/nf-d2d1_1-id2d1effect-getoutput#">Read more on docs.microsoft.com</see>.</para>
            /// </remarks>
            internal unsafe void GetOutput(win32.Graphics.Direct2D.ID2D1Image**outputImage)
            {
                fixed (ID2D1Effect*pThis = &this)
                    lpVtbl->GetOutput_19(pThis, outputImage);
            }

            private struct Vtbl
            {
                internal delegate *unmanaged[Stdcall]<ID2D1Effect*, global::System.Guid*, void **, win32.System.Com.HRESULT>QueryInterface_1;
                internal delegate *unmanaged[Stdcall]<ID2D1Effect*, uint>AddRef_2;
                internal delegate *unmanaged[Stdcall]<ID2D1Effect*, uint>Release_3;
                internal delegate *unmanaged[Stdcall]<ID2D1Effect*, uint>GetPropertyCount_4;
                internal delegate *unmanaged[Stdcall]<ID2D1Effect*, uint, win32.System.SystemServices.PWSTR, uint, win32.System.Com.HRESULT>GetPropertyName_5;
                internal delegate *unmanaged[Stdcall]<ID2D1Effect*, uint, uint>GetPropertyNameLength_6;
                internal delegate *unmanaged[Stdcall]<ID2D1Effect*, uint, win32.Graphics.Direct2D.D2D1_PROPERTY_TYPE>GetType_7;
                internal delegate *unmanaged[Stdcall]<ID2D1Effect*, win32.System.SystemServices.PCWSTR, uint>GetPropertyIndex_8;
                internal delegate *unmanaged[Stdcall]<ID2D1Effect*, win32.System.SystemServices.PCWSTR, win32.Graphics.Direct2D.D2D1_PROPERTY_TYPE, byte *, uint, win32.System.Com.HRESULT>SetValueByName_9;
                internal delegate *unmanaged[Stdcall]<ID2D1Effect*, uint, win32.Graphics.Direct2D.D2D1_PROPERTY_TYPE, byte *, uint, win32.System.Com.HRESULT>SetValue_10;
                internal delegate *unmanaged[Stdcall]<ID2D1Effect*, win32.System.SystemServices.PCWSTR, win32.Graphics.Direct2D.D2D1_PROPERTY_TYPE, byte *, uint, win32.System.Com.HRESULT>GetValueByName_11;
                internal delegate *unmanaged[Stdcall]<ID2D1Effect*, uint, win32.Graphics.Direct2D.D2D1_PROPERTY_TYPE, byte *, uint, win32.System.Com.HRESULT>GetValue_12;
                internal delegate *unmanaged[Stdcall]<ID2D1Effect*, uint, uint>GetValueSize_13;
                internal delegate *unmanaged[Stdcall]<ID2D1Effect*, uint, win32.Graphics.Direct2D.ID2D1Properties**, win32.System.Com.HRESULT>GetSubProperties_14;
                internal delegate *unmanaged[Stdcall]<ID2D1Effect*, uint, win32.Graphics.Direct2D.ID2D1Image*, win32.System.SystemServices.BOOL, void>SetInput_15;
                internal delegate *unmanaged[Stdcall]<ID2D1Effect*, uint, win32.System.Com.HRESULT>SetInputCount_16;
                internal delegate *unmanaged[Stdcall]<ID2D1Effect*, uint, win32.Graphics.Direct2D.ID2D1Image**, void>GetInput_17;
                internal delegate *unmanaged[Stdcall]<ID2D1Effect*, uint>GetInputCount_18;
                internal delegate *unmanaged[Stdcall]<ID2D1Effect*, win32.Graphics.Direct2D.ID2D1Image**, void>GetOutput_19;
            }

            private Vtbl*lpVtbl;
        }
    }
}