// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable CS1591, CS1573, CS0465, CS0649, CS8019, CS1570, CS1584, CS1658
namespace Windows.Win32
{
    using global::System;
    using global::System.Diagnostics;
    using global::System.Runtime.CompilerServices;
    using global::System.Runtime.InteropServices;
    using win32 = global::Windows.Win32;

    namespace UI.KeyboardAndMouseInput
    {
        /// <summary>Contains information about a raw input device.</summary>
        /// <remarks>
        /// <para><see href = "https://docs.microsoft.com/windows/win32/api//winuser/ns-winuser-rawinputdevicelist">Learn more about this API from docs.microsoft.com</see>.</para>
        /// </remarks>
        internal partial struct RAWINPUTDEVICELIST
        {
            /// <summary>
            /// <para>Type: <b>HANDLE</b></para>
            /// <para>A handle to the raw input device.</para>
            /// <para><see href = "https://docs.microsoft.com/windows/win32/api//winuser/ns-winuser-rawinputdevicelist#members">Read more on docs.microsoft.com</see>.</para>
            /// </summary>
            internal win32.System.SystemServices.HANDLE hDevice;
            /// <summary>Type: <b>DWORD</b></summary>
            internal win32.UI.KeyboardAndMouseInput.RID_DEVICE_INFO_TYPE dwType;
        }
    }
}