// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable CS1591, CS1573, CS0465, CS0649, CS8019, CS1570, CS1584, CS1658
namespace Windows.Win32
{
    using global::System;
    using global::System.Diagnostics;
    using global::System.Runtime.CompilerServices;
    using global::System.Runtime.InteropServices;
    using win32 = global::Windows.Win32;

    namespace Graphics.Direct3D10
    {
        /// <summary>Provides access to subresource data in a 2D texture.</summary>
        /// <remarks>
        /// <para>This structure is used in a call to <a href = "https://docs.microsoft.com/windows/desktop/api/d3d10/nf-d3d10-id3d10texture2d-map">Map</a>.</para>
        /// <para>To illustrate the row pitch, assume an uncompressed 2D texture with mipmap levels, as shown in the following illustration.</para>
        /// <para></para>
        /// <para>This doc was truncated.</para>
        /// <para><see href = "https://docs.microsoft.com/windows/win32/api//d3d10/ns-d3d10-d3d10_mapped_texture2d#">Read more on docs.microsoft.com</see>.</para>
        /// </remarks>
        internal partial struct D3D10_MAPPED_TEXTURE2D
        {
            /// <summary>
            /// <para>Type: <b>void*</b></para>
            /// <para>Pointer to the data.</para>
            /// <para><see href = "https://docs.microsoft.com/windows/win32/api//d3d10/ns-d3d10-d3d10_mapped_texture2d#members">Read more on docs.microsoft.com</see>.</para>
            /// </summary>
            internal unsafe void *pData;
            /// <summary>
            /// <para>Type: <b><a href = "https://docs.microsoft.com/windows/desktop/WinProg/windows-data-types">UINT</a></b></para>
            /// <para>The pitch, or width, or physical size (in bytes), of one row of an uncompressed texture. A block-compressed texture is encoded in 4x4 blocks (see <a href = "https://docs.microsoft.com/windows/desktop/direct3d10/d3d10-graphics-programming-guide-resources-block-compression">virtual size vs physical size</a>) ; therefore, <b>RowPitch</b> is the number of bytes in a block of 4x4 texels.</para>
            /// <para><see href = "https://docs.microsoft.com/windows/win32/api//d3d10/ns-d3d10-d3d10_mapped_texture2d#members">Read more on docs.microsoft.com</see>.</para>
            /// </summary>
            internal uint RowPitch;
        }
    }
}