// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable CS1591, CS1573, CS0465, CS0649, CS8019, CS1570, CS1584, CS1658
namespace Windows.Win32
{
    using global::System;
    using global::System.Diagnostics;
    using global::System.Runtime.CompilerServices;
    using global::System.Runtime.InteropServices;
    using win32 = global::Windows.Win32;

    namespace Graphics.Direct3D10
    {
        /// <summary>Describes a shader input.</summary>
        /// <remarks>
        /// <para>The <b>D3D10_SHADER_DEBUG_INPUT_INFO</b> structure is used with the <a href = "https://docs.microsoft.com/windows/win32/api/d3d10_1shader/ns-d3d10_1shader-d3d10_shader_debug_info">D3D10_SHADER_DEBUG_INFO</a> structure.</para>
        /// <para><see href = "https://docs.microsoft.com/windows/win32/api//d3d10_1shader/ns-d3d10_1shader-d3d10_shader_debug_input_info#">Read more on docs.microsoft.com</see>.</para>
        /// </remarks>
        internal partial struct D3D10_SHADER_DEBUG_INPUT_INFO
        {
            /// <summary>
            /// <para>Type: <b><a href = "https://docs.microsoft.com/windows/desktop/WinProg/windows-data-types">UINT</a></b></para>
            /// <para>Index into array of variables to initialize.</para>
            /// <para><see href = "https://docs.microsoft.com/windows/win32/api//d3d10_1shader/ns-d3d10_1shader-d3d10_shader_debug_input_info#members">Read more on docs.microsoft.com</see>.</para>
            /// </summary>
            internal uint Var;
            /// <summary>
            /// <para>Type: <b><a href = "https://docs.microsoft.com/windows/win32/api/d3d10_1shader/ne-d3d10_1shader-d3d10_shader_debug_regtype">D3D10_SHADER_DEBUG_REGTYPE</a></b></para>
            /// <para>Must be D3D10_SHADER_DEBUG_REG_INPUT, D3D10_SHADER_DEBUG_REG_CBUFFER or D3D10_SHADER_DEBUG_REG_TBUFFER.</para>
            /// <para><see href = "https://docs.microsoft.com/windows/win32/api//d3d10_1shader/ns-d3d10_1shader-d3d10_shader_debug_input_info#members">Read more on docs.microsoft.com</see>.</para>
            /// </summary>
            internal win32.Graphics.Direct3D10.D3D10_SHADER_DEBUG_REGTYPE InitialRegisterSet;
            /// <summary>
            /// <para>Type: <b><a href = "https://docs.microsoft.com/windows/desktop/WinProg/windows-data-types">UINT</a></b></para>
            /// <para>Will contain a cbuffer or tbuffer slot, geometry shader input primitive number, identifying register for an indexable temp, or -1.</para>
            /// <para><see href = "https://docs.microsoft.com/windows/win32/api//d3d10_1shader/ns-d3d10_1shader-d3d10_shader_debug_input_info#members">Read more on docs.microsoft.com</see>.</para>
            /// </summary>
            internal uint InitialBank;
            /// <summary>
            /// <para>Type: <b><a href = "https://docs.microsoft.com/windows/desktop/WinProg/windows-data-types">UINT</a></b></para>
            /// <para>Register in register set.  <b>InitialRegister</b> will be -1 if it is temporary.</para>
            /// <para><see href = "https://docs.microsoft.com/windows/win32/api//d3d10_1shader/ns-d3d10_1shader-d3d10_shader_debug_input_info#members">Read more on docs.microsoft.com</see>.</para>
            /// </summary>
            internal uint InitialRegister;
            /// <summary>
            /// <para>Type: <b><a href = "https://docs.microsoft.com/windows/desktop/WinProg/windows-data-types">UINT</a></b></para>
            /// <para>Gives the component.  <b>InitialComponent</b> will be -1 it is temporary.</para>
            /// <para><see href = "https://docs.microsoft.com/windows/win32/api//d3d10_1shader/ns-d3d10_1shader-d3d10_shader_debug_input_info#members">Read more on docs.microsoft.com</see>.</para>
            /// </summary>
            internal uint InitialComponent;
            /// <summary>
            /// <para>Type: <b><a href = "https://docs.microsoft.com/windows/desktop/WinProg/windows-data-types">UINT</a></b></para>
            /// <para>Initial value if the variable is a literal.</para>
            /// <para><see href = "https://docs.microsoft.com/windows/win32/api//d3d10_1shader/ns-d3d10_1shader-d3d10_shader_debug_input_info#members">Read more on docs.microsoft.com</see>.</para>
            /// </summary>
            internal uint InitialValue;
        }
    }
}