// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable CS1591, CS1573, CS0465, CS0649, CS8019, CS1570, CS1584, CS1658
namespace Windows.Win32
{
    using global::System;
    using global::System.Diagnostics;
    using global::System.Runtime.CompilerServices;
    using global::System.Runtime.InteropServices;
    using win32 = global::Windows.Win32;

    namespace Graphics.Direct3D10
    {
        [Guid("1BF63C95-2650-405D-99C1-3636BD1DA0A1")]
        internal unsafe struct ID3D10ShaderReflectionVariable
        {
            /// <inheritdoc cref = "GetDesc(win32.Graphics.Direct3D10.D3D10_SHADER_VARIABLE_DESC*)"/>
            internal unsafe win32.System.Com.HRESULT GetDesc(out win32.Graphics.Direct3D10.D3D10_SHADER_VARIABLE_DESC pDesc)
            {
                fixed (win32.Graphics.Direct3D10.D3D10_SHADER_VARIABLE_DESC*pDescLocal = &pDesc)
                {
                    win32.System.Com.HRESULT __result = this.GetDesc(pDescLocal);
                    return __result;
                }
            }

            /// <summary>Get a shader-variable description.</summary>
            /// <param name = "pDesc">
            /// <para>Type: <b><a href = "https://docs.microsoft.com/windows/desktop/api/d3d10shader/ns-d3d10shader-d3d10_shader_variable_desc">D3D10_SHADER_VARIABLE_DESC</a>*</b></para>
            /// <para>A pointer to a shader-variable description (see <a href = "https://docs.microsoft.com/windows/desktop/api/d3d10shader/ns-d3d10shader-d3d10_shader_variable_desc">D3D10_SHADER_VARIABLE_DESC</a>).</para>
            /// <para><see href = "https://docs.microsoft.com/windows/win32/api//d3d10shader/nf-d3d10shader-id3d10shaderreflectionvariable-getdesc#parameters">Read more on docs.microsoft.com</see>.</para>
            /// </param>
            /// <returns>
            /// <para>Type: <b><a href = "/windows/win32/com/structure-of-com-error-codes">HRESULT</a></b></para>
            /// <para>Returns one of the following <a href = "/windows/desktop/direct3d10/d3d10-graphics-reference-returnvalues">Direct3D 10 Return Codes</a>.</para>
            /// </returns>
            /// <remarks>
            /// <para><see href = "https://docs.microsoft.com/windows/win32/api//d3d10shader/nf-d3d10shader-id3d10shaderreflectionvariable-getdesc">Learn more about this API from docs.microsoft.com</see>.</para>
            /// </remarks>
            internal unsafe win32.System.Com.HRESULT GetDesc(win32.Graphics.Direct3D10.D3D10_SHADER_VARIABLE_DESC*pDesc)
            {
                fixed (ID3D10ShaderReflectionVariable*pThis = &this)
                    return lpVtbl->GetDesc_1(pThis, pDesc);
            }

            /// <summary>Get a shader-variable type.</summary>
            /// <returns>
            /// <para>Type: <b><a href = "/windows/desktop/api/d3d10shader/nn-d3d10shader-id3d10shaderreflectiontype">ID3D10ShaderReflectionType</a>*</b></para>
            /// <para>A pointer to a <a href = "/windows/desktop/api/d3d10shader/nn-d3d10shader-id3d10shaderreflectiontype">ID3D10ShaderReflectionType Interface</a>.</para>
            /// </returns>
            /// <remarks>
            /// <para><see href = "https://docs.microsoft.com/windows/win32/api//d3d10shader/nf-d3d10shader-id3d10shaderreflectionvariable-gettype">Learn more about this API from docs.microsoft.com</see>.</para>
            /// </remarks>
            internal new unsafe win32.Graphics.Direct3D10.ID3D10ShaderReflectionType*GetType()
            {
                fixed (ID3D10ShaderReflectionVariable*pThis = &this)
                    return lpVtbl->GetType_2(pThis);
            }

            private struct Vtbl
            {
                internal delegate *unmanaged[Stdcall]<ID3D10ShaderReflectionVariable*, win32.Graphics.Direct3D10.D3D10_SHADER_VARIABLE_DESC*, win32.System.Com.HRESULT>GetDesc_1;
                internal delegate *unmanaged[Stdcall]<ID3D10ShaderReflectionVariable*, win32.Graphics.Direct3D10.ID3D10ShaderReflectionType*>GetType_2;
            }

            private Vtbl*lpVtbl;
        }
    }
}