// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable CS1591, CS1573, CS0465, CS0649, CS8019, CS1570, CS1584, CS1658
namespace Windows.Win32
{
    using global::System;
    using global::System.Diagnostics;
    using global::System.Runtime.CompilerServices;
    using global::System.Runtime.InteropServices;
    using win32 = global::Windows.Win32;

    namespace Graphics.Dxgi
    {
        /// <summary>Identifies the granularity at which the graphics processing unit (GPU) can be preempted from performing its current graphics rendering task.</summary>
        /// <remarks>
        /// <para>You call the <a href = "https://docs.microsoft.com/windows/desktop/api/dxgi1_2/nf-dxgi1_2-idxgiadapter2-getdesc2">IDXGIAdapter2::GetDesc2</a> method to retrieve the granularity level at which the GPU can be preempted from performing its current graphics rendering task. The operating system specifies the graphics granularity level in the  <b>GraphicsPreemptionGranularity</b> member of the <a href = "https://docs.microsoft.com/windows/desktop/api/dxgi1_2/ns-dxgi1_2-dxgi_adapter_desc2">DXGI_ADAPTER_DESC2</a> structure.</para>
        /// <para>The following figure shows granularity of graphics rendering tasks.</para>
        /// <para></para>
        /// <para>This doc was truncated.</para>
        /// <para><see href = "https://docs.microsoft.com/windows/win32/api//dxgi1_2/ne-dxgi1_2-dxgi_graphics_preemption_granularity#">Read more on docs.microsoft.com</see>.</para>
        /// </remarks>
        internal enum DXGI_GRAPHICS_PREEMPTION_GRANULARITY
        {
            /// <summary>Indicates the preemption granularity as a DMA buffer.</summary>
            DXGI_GRAPHICS_PREEMPTION_DMA_BUFFER_BOUNDARY = 0,
            /// <summary>Indicates the preemption granularity as a graphics primitive. A primitive is a section in a DMA buffer and can be a group of triangles.</summary>
            DXGI_GRAPHICS_PREEMPTION_PRIMITIVE_BOUNDARY = 1,
            /// <summary>Indicates the preemption granularity as a triangle. A triangle is a part of a primitive.</summary>
            DXGI_GRAPHICS_PREEMPTION_TRIANGLE_BOUNDARY = 2,
            /// <summary>Indicates the preemption granularity as a pixel. A pixel is a part of a triangle.</summary>
            DXGI_GRAPHICS_PREEMPTION_PIXEL_BOUNDARY = 3,
            /// <summary>Indicates the preemption granularity as a graphics instruction. A graphics instruction operates on a pixel.</summary>
            DXGI_GRAPHICS_PREEMPTION_INSTRUCTION_BOUNDARY = 4,
        }
    }
}