// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable CS1591, CS1573, CS0465, CS0649, CS8019, CS1570, CS1584, CS1658
namespace Windows.Win32
{
    using global::System;
    using global::System.Diagnostics;
    using global::System.Runtime.CompilerServices;
    using global::System.Runtime.InteropServices;
    using win32 = global::Windows.Win32;

    namespace Graphics.Direct3D12
    {
        /// <summary>Describes a resource to resolve to at the conclusion of a render pass.</summary>
        /// <remarks>
        /// <para><see href = "https://docs.microsoft.com/windows/win32/api//d3d12/ns-d3d12-d3d12_render_pass_ending_access_resolve_parameters">Learn more about this API from docs.microsoft.com</see>.</para>
        /// </remarks>
        internal partial struct D3D12_RENDER_PASS_ENDING_ACCESS_RESOLVE_PARAMETERS
        {
            /// <summary>A pointer to an <a href = "https://docs.microsoft.com/windows/desktop/api/d3d12/nn-d3d12-id3d12resource">ID3D12Resource</a>. The source resource.</summary>
            internal unsafe win32.Graphics.Direct3D12.ID3D12Resource*pSrcResource;
            /// <summary>A pointer to an <a href = "https://docs.microsoft.com/windows/desktop/api/d3d12/nn-d3d12-id3d12resource">ID3D12Resource</a>. The destination resource.</summary>
            internal unsafe win32.Graphics.Direct3D12.ID3D12Resource*pDstResource;
            /// <summary>A <b>UINT</b>. The number of subresources.</summary>
            internal uint SubresourceCount;
            /// <summary>
            /// <para>A pointer to a constant array of <a href = "https://docs.microsoft.com/windows/desktop/api/d3d12/ns-d3d12-d3d12_render_pass_ending_access_resolve_subresource_parameters">D3D12_RENDER_PASS_ENDING_ACCESS_RESOLVE_SUBRESOURCE_PARAMETERS</a>. These subresources can be a subset of the render target's array slices, but you can't target subresources that aren't part of the render target view (RTV) or the depth/stencil view (DSV).</para>
            /// <para>> [!NOTE] > This pointer is directly referenced by the command list, and the memory for this array must remain alive and intact until [EndRenderPass](nf-d3d12-id3d12graphicscommandlist4-endrenderpass.md) is called.</para>
            /// <para><see href = "https://docs.microsoft.com/windows/win32/api//d3d12/ns-d3d12-d3d12_render_pass_ending_access_resolve_parameters#members">Read more on docs.microsoft.com</see>.</para>
            /// </summary>
            internal unsafe win32.Graphics.Direct3D12.D3D12_RENDER_PASS_ENDING_ACCESS_RESOLVE_SUBRESOURCE_PARAMETERS*pSubresourceParameters;
            /// <summary>A <a href = "https://docs.microsoft.com/windows/desktop/api/dxgiformat/ne-dxgiformat-dxgi_format">DXGI_FORMAT</a>. The data format of the resources.</summary>
            internal win32.Graphics.Dxgi.DXGI_FORMAT Format;
            /// <summary>A <a href = "https://docs.microsoft.com/windows/desktop/api/d3d12/ne-d3d12-d3d12_resolve_mode">D3D12_RESOLVE_MODE</a>. The resolve operation.</summary>
            internal win32.Graphics.Direct3D12.D3D12_RESOLVE_MODE ResolveMode;
            /// <summary>A <b>BOOL</b>. <b>TRUE</b> to preserve the resolve source, otherwise <b>FALSE</b>.</summary>
            internal win32.System.SystemServices.BOOL PreserveResolveSource;
        }
    }
}