// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable CS1591, CS1573, CS0465, CS0649, CS8019, CS1570, CS1584, CS1658
namespace Windows.Win32
{
    using global::System;
    using global::System.Diagnostics;
    using global::System.Runtime.CompilerServices;
    using global::System.Runtime.InteropServices;
    using static Windows.Win32.ApiSets;
    using win32 = global::Windows.Win32;

    namespace Graphics.Direct3D12
    {
        [Guid("F75B68D6-D1FD-4707-AAFD-FA6F4C0E3BF4")]
        internal unsafe struct IHolographicCameraRenderingParametersInterop
        {
            /// <inheritdoc cref = "QueryInterface(global::System.Guid*, void **)"/>
            internal unsafe win32.System.Com.HRESULT QueryInterface(in global::System.Guid riid, out void *ppvObject)
            {
                fixed (void **ppvObjectLocal = &ppvObject)
                {
                    fixed (global::System.Guid*riidLocal = &riid)
                    {
                        win32.System.Com.HRESULT __result = this.QueryInterface(riidLocal, ppvObjectLocal);
                        return __result;
                    }
                }
            }

            internal unsafe win32.System.Com.HRESULT QueryInterface(global::System.Guid*riid, void **ppvObject)
            {
                fixed (IHolographicCameraRenderingParametersInterop*pThis = &this)
                    return lpVtbl->QueryInterface_1(pThis, riid, ppvObject);
            }

            internal uint AddRef()
            {
                fixed (IHolographicCameraRenderingParametersInterop*pThis = &this)
                    return lpVtbl->AddRef_2(pThis);
            }

            internal uint Release()
            {
                fixed (IHolographicCameraRenderingParametersInterop*pThis = &this)
                    return lpVtbl->Release_3(pThis);
            }

            /// <inheritdoc cref = "GetIids(uint *, global::System.Guid**)"/>
            internal unsafe win32.System.Com.HRESULT GetIids(out uint iidCount, global::System.Guid**iids)
            {
                fixed (uint *iidCountLocal = &iidCount)
                {
                    win32.System.Com.HRESULT __result = this.GetIids(iidCountLocal, iids);
                    return __result;
                }
            }

            internal unsafe win32.System.Com.HRESULT GetIids(uint *iidCount, [Optional] global::System.Guid**iids)
            {
                fixed (IHolographicCameraRenderingParametersInterop*pThis = &this)
                    return lpVtbl->GetIids_4(pThis, iidCount, iids);
            }

            /// <inheritdoc cref = "GetRuntimeClassName(win32.System.WinRT.HSTRING*)"/>
            internal unsafe win32.System.Com.HRESULT GetRuntimeClassName(out WindowsDeleteStringSafeHandle className)
            {
                win32.System.WinRT.HSTRING classNameLocal;
                win32.System.Com.HRESULT __result = this.GetRuntimeClassName(&classNameLocal);
                className = new WindowsDeleteStringSafeHandle(classNameLocal, ownsHandle: true);
                return __result;
            }

            internal unsafe win32.System.Com.HRESULT GetRuntimeClassName([Optional] win32.System.WinRT.HSTRING*className)
            {
                fixed (IHolographicCameraRenderingParametersInterop*pThis = &this)
                    return lpVtbl->GetRuntimeClassName_5(pThis, className);
            }

            /// <inheritdoc cref = "GetTrustLevel(win32.System.WinRT.TrustLevel*)"/>
            internal unsafe win32.System.Com.HRESULT GetTrustLevel(out win32.System.WinRT.TrustLevel trustLevel)
            {
                fixed (win32.System.WinRT.TrustLevel*trustLevelLocal = &trustLevel)
                {
                    win32.System.Com.HRESULT __result = this.GetTrustLevel(trustLevelLocal);
                    return __result;
                }
            }

            internal unsafe win32.System.Com.HRESULT GetTrustLevel(win32.System.WinRT.TrustLevel*trustLevel)
            {
                fixed (IHolographicCameraRenderingParametersInterop*pThis = &this)
                    return lpVtbl->GetTrustLevel_6(pThis, trustLevel);
            }

            internal unsafe win32.System.Com.HRESULT CommitDirect3D12Resource(win32.Graphics.Direct3D12.ID3D12Resource*pColorResourceToCommit, win32.Graphics.Direct3D12.ID3D12Fence*pColorResourceFence, ulong colorResourceFenceSignalValue)
            {
                fixed (IHolographicCameraRenderingParametersInterop*pThis = &this)
                    return lpVtbl->CommitDirect3D12Resource_7(pThis, pColorResourceToCommit, pColorResourceFence, colorResourceFenceSignalValue);
            }

            internal unsafe win32.System.Com.HRESULT CommitDirect3D12ResourceWithDepthData(win32.Graphics.Direct3D12.ID3D12Resource*pColorResourceToCommit, win32.Graphics.Direct3D12.ID3D12Fence*pColorResourceFence, ulong colorResourceFenceSignalValue, win32.Graphics.Direct3D12.ID3D12Resource*pDepthResourceToCommit, win32.Graphics.Direct3D12.ID3D12Fence*pDepthResourceFence, ulong depthResourceFenceSignalValue)
            {
                fixed (IHolographicCameraRenderingParametersInterop*pThis = &this)
                    return lpVtbl->CommitDirect3D12ResourceWithDepthData_8(pThis, pColorResourceToCommit, pColorResourceFence, colorResourceFenceSignalValue, pDepthResourceToCommit, pDepthResourceFence, depthResourceFenceSignalValue);
            }

            private struct Vtbl
            {
                internal delegate *unmanaged[Stdcall]<IHolographicCameraRenderingParametersInterop*, global::System.Guid*, void **, win32.System.Com.HRESULT>QueryInterface_1;
                internal delegate *unmanaged[Stdcall]<IHolographicCameraRenderingParametersInterop*, uint>AddRef_2;
                internal delegate *unmanaged[Stdcall]<IHolographicCameraRenderingParametersInterop*, uint>Release_3;
                internal delegate *unmanaged[Stdcall]<IHolographicCameraRenderingParametersInterop*, uint *, global::System.Guid**, win32.System.Com.HRESULT>GetIids_4;
                internal delegate *unmanaged[Stdcall]<IHolographicCameraRenderingParametersInterop*, win32.System.WinRT.HSTRING*, win32.System.Com.HRESULT>GetRuntimeClassName_5;
                internal delegate *unmanaged[Stdcall]<IHolographicCameraRenderingParametersInterop*, win32.System.WinRT.TrustLevel*, win32.System.Com.HRESULT>GetTrustLevel_6;
                internal delegate *unmanaged[Stdcall]<IHolographicCameraRenderingParametersInterop*, win32.Graphics.Direct3D12.ID3D12Resource*, win32.Graphics.Direct3D12.ID3D12Fence*, ulong, win32.System.Com.HRESULT>CommitDirect3D12Resource_7;
                internal delegate *unmanaged[Stdcall]<IHolographicCameraRenderingParametersInterop*, win32.Graphics.Direct3D12.ID3D12Resource*, win32.Graphics.Direct3D12.ID3D12Fence*, ulong, win32.Graphics.Direct3D12.ID3D12Resource*, win32.Graphics.Direct3D12.ID3D12Fence*, ulong, win32.System.Com.HRESULT>CommitDirect3D12ResourceWithDepthData_8;
            }

            private Vtbl*lpVtbl;
        }
    }
}