// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable CS1591, CS1573, CS0465, CS0649, CS8019, CS1570, CS1584, CS1658
namespace Windows.Win32
{
    using global::System;
    using global::System.Diagnostics;
    using global::System.Runtime.CompilerServices;
    using global::System.Runtime.InteropServices;
    using win32 = global::Windows.Win32;

    namespace System.Diagnostics.ToolHelp
    {
        /// <summary>Describes an entry from a list of the threads executing in the system when a snapshot was taken.</summary>
        /// <remarks>
        /// <para><see href = "https://docs.microsoft.com/windows/win32/api//tlhelp32/ns-tlhelp32-threadentry32">Learn more about this API from docs.microsoft.com</see>.</para>
        /// </remarks>
        internal partial struct THREADENTRY32
        {
            /// <summary>
            /// <para>The size of the structure, in bytes. Before calling the <a href = "https://docs.microsoft.com/windows/desktop/api/tlhelp32/nf-tlhelp32-thread32first">Thread32First</a> function, set this member to <c>sizeof(THREADENTRY32)</c>. If you do not initialize <b>dwSize</b>, <b>Thread32First</b> fails.</para>
            /// <para><see href = "https://docs.microsoft.com/windows/win32/api//tlhelp32/ns-tlhelp32-threadentry32#members">Read more on docs.microsoft.com</see>.</para>
            /// </summary>
            internal uint dwSize;
            /// <summary>This member is no longer used and is always set to zero.</summary>
            internal uint cntUsage;
            /// <summary>
            /// <para>The thread identifier, compatible with the thread identifier returned by the <a href = "https://docs.microsoft.com/windows/desktop/api/processthreadsapi/nf-processthreadsapi-createprocessa">CreateProcess</a> function.</para>
            /// <para><see href = "https://docs.microsoft.com/windows/win32/api//tlhelp32/ns-tlhelp32-threadentry32#members">Read more on docs.microsoft.com</see>.</para>
            /// </summary>
            internal uint th32ThreadID;
            /// <summary>The identifier of the process that created the thread.</summary>
            internal uint th32OwnerProcessID;
            /// <summary>The kernel base priority level assigned to the thread. The priority is a number from 0 to 31, with 0 representing the lowest possible thread priority. For more information, see <b>KeQueryPriorityThread</b>.</summary>
            internal int tpBasePri;
            /// <summary>This member is no longer used and is always set to zero.</summary>
            internal int tpDeltaPri;
            /// <summary>This member is no longer used and is always set to zero.</summary>
            internal uint dwFlags;
        }
    }
}