// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable CS1591, CS1573, CS0465, CS0649, CS8019, CS1570, CS1584, CS1658
namespace Windows.Win32
{
    using global::System;
    using global::System.Diagnostics;
    using global::System.Runtime.CompilerServices;
    using global::System.Runtime.InteropServices;
    using win32 = global::Windows.Win32;

    namespace Graphics.Hlsl
    {
        [Guid("A005A9D9-B8BB-4594-B5C9-0E633BEC4D37")]
        internal unsafe struct IDxcCompiler2
        {
            /// <inheritdoc cref = "QueryInterface(global::System.Guid*, void **)"/>
            internal unsafe win32.System.Com.HRESULT QueryInterface(in global::System.Guid riid, out void *ppvObject)
            {
                fixed (void **ppvObjectLocal = &ppvObject)
                {
                    fixed (global::System.Guid*riidLocal = &riid)
                    {
                        win32.System.Com.HRESULT __result = this.QueryInterface(riidLocal, ppvObjectLocal);
                        return __result;
                    }
                }
            }

            internal unsafe win32.System.Com.HRESULT QueryInterface(global::System.Guid*riid, void **ppvObject)
            {
                fixed (IDxcCompiler2*pThis = &this)
                    return lpVtbl->QueryInterface_1(pThis, riid, ppvObject);
            }

            internal uint AddRef()
            {
                fixed (IDxcCompiler2*pThis = &this)
                    return lpVtbl->AddRef_2(pThis);
            }

            internal uint Release()
            {
                fixed (IDxcCompiler2*pThis = &this)
                    return lpVtbl->Release_3(pThis);
            }

            /// <inheritdoc cref = "Compile(win32.Graphics.Hlsl.IDxcBlob*, win32.System.SystemServices.PCWSTR, win32.System.SystemServices.PCWSTR, win32.System.SystemServices.PCWSTR, win32.System.SystemServices.PWSTR*, uint, win32.Graphics.Hlsl.DxcDefine*, uint, win32.Graphics.Hlsl.IDxcIncludeHandler*, win32.Graphics.Hlsl.IDxcOperationResult**)"/>
            internal unsafe win32.System.Com.HRESULT Compile(win32.Graphics.Hlsl.IDxcBlob*pSource, string pSourceName, string pEntryPoint, string pTargetProfile, Span<win32.System.SystemServices.PWSTR> pArguments, ReadOnlySpan<win32.Graphics.Hlsl.DxcDefine> pDefines, win32.Graphics.Hlsl.IDxcIncludeHandler*pIncludeHandler, win32.Graphics.Hlsl.IDxcOperationResult**ppResult)
            {
                fixed (win32.Graphics.Hlsl.DxcDefine*pDefinesLocal = pDefines)
                {
                    fixed (win32.System.SystemServices.PWSTR*pArgumentsLocal = pArguments)
                    {
                        fixed (char *pTargetProfileLocal = pTargetProfile)
                        {
                            fixed (char *pEntryPointLocal = pEntryPoint)
                            {
                                fixed (char *pSourceNameLocal = pSourceName)
                                {
                                    win32.System.Com.HRESULT __result = this.Compile(pSource, pSourceNameLocal, pEntryPointLocal, pTargetProfileLocal, pArgumentsLocal, (uint)pArguments.Length, pDefinesLocal, (uint)pDefines.Length, pIncludeHandler, ppResult);
                                    return __result;
                                }
                            }
                        }
                    }
                }
            }

            internal unsafe win32.System.Com.HRESULT Compile(win32.Graphics.Hlsl.IDxcBlob*pSource, win32.System.SystemServices.PCWSTR pSourceName, win32.System.SystemServices.PCWSTR pEntryPoint, win32.System.SystemServices.PCWSTR pTargetProfile, win32.System.SystemServices.PWSTR*pArguments, uint argCount, win32.Graphics.Hlsl.DxcDefine*pDefines, uint defineCount, [Optional] win32.Graphics.Hlsl.IDxcIncludeHandler*pIncludeHandler, win32.Graphics.Hlsl.IDxcOperationResult**ppResult)
            {
                fixed (IDxcCompiler2*pThis = &this)
                    return lpVtbl->Compile_4(pThis, pSource, pSourceName, pEntryPoint, pTargetProfile, pArguments, argCount, pDefines, defineCount, pIncludeHandler, ppResult);
            }

            /// <inheritdoc cref = "Preprocess(win32.Graphics.Hlsl.IDxcBlob*, win32.System.SystemServices.PCWSTR, win32.System.SystemServices.PWSTR*, uint, win32.Graphics.Hlsl.DxcDefine*, uint, win32.Graphics.Hlsl.IDxcIncludeHandler*, win32.Graphics.Hlsl.IDxcOperationResult**)"/>
            internal unsafe win32.System.Com.HRESULT Preprocess(win32.Graphics.Hlsl.IDxcBlob*pSource, string pSourceName, Span<win32.System.SystemServices.PWSTR> pArguments, ReadOnlySpan<win32.Graphics.Hlsl.DxcDefine> pDefines, win32.Graphics.Hlsl.IDxcIncludeHandler*pIncludeHandler, win32.Graphics.Hlsl.IDxcOperationResult**ppResult)
            {
                fixed (win32.Graphics.Hlsl.DxcDefine*pDefinesLocal = pDefines)
                {
                    fixed (win32.System.SystemServices.PWSTR*pArgumentsLocal = pArguments)
                    {
                        fixed (char *pSourceNameLocal = pSourceName)
                        {
                            win32.System.Com.HRESULT __result = this.Preprocess(pSource, pSourceNameLocal, pArgumentsLocal, (uint)pArguments.Length, pDefinesLocal, (uint)pDefines.Length, pIncludeHandler, ppResult);
                            return __result;
                        }
                    }
                }
            }

            internal unsafe win32.System.Com.HRESULT Preprocess(win32.Graphics.Hlsl.IDxcBlob*pSource, win32.System.SystemServices.PCWSTR pSourceName, win32.System.SystemServices.PWSTR*pArguments, uint argCount, win32.Graphics.Hlsl.DxcDefine*pDefines, uint defineCount, [Optional] win32.Graphics.Hlsl.IDxcIncludeHandler*pIncludeHandler, win32.Graphics.Hlsl.IDxcOperationResult**ppResult)
            {
                fixed (IDxcCompiler2*pThis = &this)
                    return lpVtbl->Preprocess_5(pThis, pSource, pSourceName, pArguments, argCount, pDefines, defineCount, pIncludeHandler, ppResult);
            }

            internal unsafe win32.System.Com.HRESULT Disassemble(win32.Graphics.Hlsl.IDxcBlob*pSource, win32.Graphics.Hlsl.IDxcBlobEncoding**ppDisassembly)
            {
                fixed (IDxcCompiler2*pThis = &this)
                    return lpVtbl->Disassemble_6(pThis, pSource, ppDisassembly);
            }

            /// <inheritdoc cref = "CompileWithDebug(win32.Graphics.Hlsl.IDxcBlob*, win32.System.SystemServices.PCWSTR, win32.System.SystemServices.PCWSTR, win32.System.SystemServices.PCWSTR, win32.System.SystemServices.PWSTR*, uint, win32.Graphics.Hlsl.DxcDefine*, uint, win32.Graphics.Hlsl.IDxcIncludeHandler*, win32.Graphics.Hlsl.IDxcOperationResult**, win32.System.SystemServices.PWSTR*, win32.Graphics.Hlsl.IDxcBlob**)"/>
            internal unsafe win32.System.Com.HRESULT CompileWithDebug(win32.Graphics.Hlsl.IDxcBlob*pSource, string pSourceName, string pEntryPoint, string pTargetProfile, Span<win32.System.SystemServices.PWSTR> pArguments, ReadOnlySpan<win32.Graphics.Hlsl.DxcDefine> pDefines, win32.Graphics.Hlsl.IDxcIncludeHandler*pIncludeHandler, win32.Graphics.Hlsl.IDxcOperationResult**ppResult, win32.System.SystemServices.PWSTR*ppDebugBlobName, win32.Graphics.Hlsl.IDxcBlob**ppDebugBlob)
            {
                fixed (win32.Graphics.Hlsl.DxcDefine*pDefinesLocal = pDefines)
                {
                    fixed (win32.System.SystemServices.PWSTR*pArgumentsLocal = pArguments)
                    {
                        fixed (char *pTargetProfileLocal = pTargetProfile)
                        {
                            fixed (char *pEntryPointLocal = pEntryPoint)
                            {
                                fixed (char *pSourceNameLocal = pSourceName)
                                {
                                    win32.System.Com.HRESULT __result = this.CompileWithDebug(pSource, pSourceNameLocal, pEntryPointLocal, pTargetProfileLocal, pArgumentsLocal, (uint)pArguments.Length, pDefinesLocal, (uint)pDefines.Length, pIncludeHandler, ppResult, ppDebugBlobName, ppDebugBlob);
                                    return __result;
                                }
                            }
                        }
                    }
                }
            }

            internal unsafe win32.System.Com.HRESULT CompileWithDebug(win32.Graphics.Hlsl.IDxcBlob*pSource, win32.System.SystemServices.PCWSTR pSourceName, win32.System.SystemServices.PCWSTR pEntryPoint, win32.System.SystemServices.PCWSTR pTargetProfile, win32.System.SystemServices.PWSTR*pArguments, uint argCount, win32.Graphics.Hlsl.DxcDefine*pDefines, uint defineCount, [Optional] win32.Graphics.Hlsl.IDxcIncludeHandler*pIncludeHandler, win32.Graphics.Hlsl.IDxcOperationResult**ppResult, [Optional] win32.System.SystemServices.PWSTR*ppDebugBlobName, [Optional] win32.Graphics.Hlsl.IDxcBlob**ppDebugBlob)
            {
                fixed (IDxcCompiler2*pThis = &this)
                    return lpVtbl->CompileWithDebug_7(pThis, pSource, pSourceName, pEntryPoint, pTargetProfile, pArguments, argCount, pDefines, defineCount, pIncludeHandler, ppResult, ppDebugBlobName, ppDebugBlob);
            }

            private struct Vtbl
            {
                internal delegate *unmanaged[Stdcall]<IDxcCompiler2*, global::System.Guid*, void **, win32.System.Com.HRESULT>QueryInterface_1;
                internal delegate *unmanaged[Stdcall]<IDxcCompiler2*, uint>AddRef_2;
                internal delegate *unmanaged[Stdcall]<IDxcCompiler2*, uint>Release_3;
                internal delegate *unmanaged[Stdcall]<IDxcCompiler2*, win32.Graphics.Hlsl.IDxcBlob*, win32.System.SystemServices.PCWSTR, win32.System.SystemServices.PCWSTR, win32.System.SystemServices.PCWSTR, win32.System.SystemServices.PWSTR*, uint, win32.Graphics.Hlsl.DxcDefine*, uint, win32.Graphics.Hlsl.IDxcIncludeHandler*, win32.Graphics.Hlsl.IDxcOperationResult**, win32.System.Com.HRESULT>Compile_4;
                internal delegate *unmanaged[Stdcall]<IDxcCompiler2*, win32.Graphics.Hlsl.IDxcBlob*, win32.System.SystemServices.PCWSTR, win32.System.SystemServices.PWSTR*, uint, win32.Graphics.Hlsl.DxcDefine*, uint, win32.Graphics.Hlsl.IDxcIncludeHandler*, win32.Graphics.Hlsl.IDxcOperationResult**, win32.System.Com.HRESULT>Preprocess_5;
                internal delegate *unmanaged[Stdcall]<IDxcCompiler2*, win32.Graphics.Hlsl.IDxcBlob*, win32.Graphics.Hlsl.IDxcBlobEncoding**, win32.System.Com.HRESULT>Disassemble_6;
                internal delegate *unmanaged[Stdcall]<IDxcCompiler2*, win32.Graphics.Hlsl.IDxcBlob*, win32.System.SystemServices.PCWSTR, win32.System.SystemServices.PCWSTR, win32.System.SystemServices.PCWSTR, win32.System.SystemServices.PWSTR*, uint, win32.Graphics.Hlsl.DxcDefine*, uint, win32.Graphics.Hlsl.IDxcIncludeHandler*, win32.Graphics.Hlsl.IDxcOperationResult**, win32.System.SystemServices.PWSTR*, win32.Graphics.Hlsl.IDxcBlob**, win32.System.Com.HRESULT>CompileWithDebug_7;
            }

            private Vtbl*lpVtbl;
        }
    }
}