// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable CS1591, CS1573, CS0465, CS0649, CS8019, CS1570, CS1584, CS1658
namespace Windows.Win32
{
    using global::System;
    using global::System.Diagnostics;
    using global::System.Runtime.CompilerServices;
    using global::System.Runtime.InteropServices;
    using win32 = global::Windows.Win32;

    internal static partial class d3dcsx
    {
        /// <summary>Creates a scan context.</summary>
        /// <param name = "pDeviceContext">
        /// <para>Type: <b><a href = "https://docs.microsoft.com/windows/desktop/api/d3d11/nn-d3d11-id3d11devicecontext">ID3D11DeviceContext</a>*</b></para>
        /// <para>The <a href = "https://docs.microsoft.com/windows/desktop/api/d3d11/nn-d3d11-id3d11devicecontext">ID3D11DeviceContext</a> the scan is associated with.</para>
        /// <para><see href = "https://docs.microsoft.com/windows/win32/api//d3dcsx/nf-d3dcsx-d3dx11createscan#parameters">Read more on docs.microsoft.com</see>.</para>
        /// </param>
        /// <param name = "MaxElementScanSize">
        /// <para>Type: <b><a href = "https://docs.microsoft.com/windows/desktop/WinProg/windows-data-types">UINT</a></b></para>
        /// <para>Maximum single scan size, in elements (FLOAT, UINT, or INT).</para>
        /// <para><see href = "https://docs.microsoft.com/windows/win32/api//d3dcsx/nf-d3dcsx-d3dx11createscan#parameters">Read more on docs.microsoft.com</see>.</para>
        /// </param>
        /// <param name = "MaxScanCount">
        /// <para>Type: <b><a href = "https://docs.microsoft.com/windows/desktop/WinProg/windows-data-types">UINT</a></b></para>
        /// <para>Maximum number of scans in multiscan.</para>
        /// <para><see href = "https://docs.microsoft.com/windows/win32/api//d3dcsx/nf-d3dcsx-d3dx11createscan#parameters">Read more on docs.microsoft.com</see>.</para>
        /// </param>
        /// <param name = "ppScan">
        /// <para>Type: <b><a href = "https://docs.microsoft.com/windows/desktop/api/d3dcsx/nn-d3dcsx-id3dx11scan">ID3DX11Scan</a>**</b></para>
        /// <para>Pointer to a <a href = "https://docs.microsoft.com/windows/desktop/api/d3dcsx/nn-d3dcsx-id3dx11scan">ID3DX11Scan Interface</a> pointer that will be set to the created interface object.</para>
        /// <para><see href = "https://docs.microsoft.com/windows/win32/api//d3dcsx/nf-d3dcsx-d3dx11createscan#parameters">Read more on docs.microsoft.com</see>.</para>
        /// </param>
        /// <returns>
        /// <para>Type: <b><a href = "/windows/win32/com/structure-of-com-error-codes">HRESULT</a></b></para>
        /// <para>The return value is one of the values listed in <a href = "/windows/desktop/direct3d11/d3d11-graphics-reference-returnvalues">Direct3D 11 Return Codes</a>.</para>
        /// </returns>
        /// <remarks>
        /// <para><see href = "https://docs.microsoft.com/windows/win32/api//d3dcsx/nf-d3dcsx-d3dx11createscan">Learn more about this API from docs.microsoft.com</see>.</para>
        /// </remarks>
        [DllImport("d3dcsx", ExactSpelling = true)]
        internal static extern unsafe win32.System.Com.HRESULT D3DX11CreateScan(win32.Graphics.Direct3D11.ID3D11DeviceContext*pDeviceContext, uint MaxElementScanSize, uint MaxScanCount, win32.Graphics.Direct3D11.ID3DX11Scan**ppScan);
        /// <summary>Creates a segmented scan context.</summary>
        /// <param name = "pDeviceContext">
        /// <para>Type: <b><a href = "https://docs.microsoft.com/windows/desktop/api/d3d11/nn-d3d11-id3d11devicecontext">ID3D11DeviceContext</a>*</b></para>
        /// <para>Pointer to an <a href = "https://docs.microsoft.com/windows/desktop/api/d3d11/nn-d3d11-id3d11devicecontext">ID3D11DeviceContext</a> interface.</para>
        /// <para><see href = "https://docs.microsoft.com/windows/win32/api//d3dcsx/nf-d3dcsx-d3dx11createsegmentedscan#parameters">Read more on docs.microsoft.com</see>.</para>
        /// </param>
        /// <param name = "MaxElementScanSize">
        /// <para>Type: <b><a href = "https://docs.microsoft.com/windows/desktop/WinProg/windows-data-types">UINT</a></b></para>
        /// <para>Maximum single scan size, in elements (FLOAT, UINT, or INT).</para>
        /// <para><see href = "https://docs.microsoft.com/windows/win32/api//d3dcsx/nf-d3dcsx-d3dx11createsegmentedscan#parameters">Read more on docs.microsoft.com</see>.</para>
        /// </param>
        /// <param name = "ppScan">
        /// <para>Type: <b><a href = "https://docs.microsoft.com/windows/desktop/api/d3dcsx/nn-d3dcsx-id3dx11segmentedscan">ID3DX11SegmentedScan</a>**</b></para>
        /// <para>Pointer to a <a href = "https://docs.microsoft.com/windows/desktop/api/d3dcsx/nn-d3dcsx-id3dx11segmentedscan">ID3DX11SegmentedScan Interface</a> pointer that will be set to the created interface object.</para>
        /// <para><see href = "https://docs.microsoft.com/windows/win32/api//d3dcsx/nf-d3dcsx-d3dx11createsegmentedscan#parameters">Read more on docs.microsoft.com</see>.</para>
        /// </param>
        /// <returns>
        /// <para>Type: <b><a href = "/windows/win32/com/structure-of-com-error-codes">HRESULT</a></b></para>
        /// <para>The return value is one of the values listed in <a href = "/windows/desktop/direct3d11/d3d11-graphics-reference-returnvalues">Direct3D 11 Return Codes</a>.</para>
        /// </returns>
        /// <remarks>
        /// <para><see href = "https://docs.microsoft.com/windows/win32/api//d3dcsx/nf-d3dcsx-d3dx11createsegmentedscan">Learn more about this API from docs.microsoft.com</see>.</para>
        /// </remarks>
        [DllImport("d3dcsx", ExactSpelling = true)]
        internal static extern unsafe win32.System.Com.HRESULT D3DX11CreateSegmentedScan(win32.Graphics.Direct3D11.ID3D11DeviceContext*pDeviceContext, uint MaxElementScanSize, win32.Graphics.Direct3D11.ID3DX11SegmentedScan**ppScan);
        /// <inheritdoc cref = "D3DX11CreateFFT(win32.Graphics.Direct3D11.ID3D11DeviceContext*, win32.Graphics.Direct3D11.D3DX11_FFT_DESC*, uint, win32.Graphics.Direct3D11.D3DX11_FFT_BUFFER_INFO*, win32.Graphics.Direct3D11.ID3DX11FFT**)"/>
        internal static unsafe win32.System.Com.HRESULT D3DX11CreateFFT(win32.Graphics.Direct3D11.ID3D11DeviceContext*pDeviceContext, in win32.Graphics.Direct3D11.D3DX11_FFT_DESC pDesc, uint Flags, out win32.Graphics.Direct3D11.D3DX11_FFT_BUFFER_INFO pBufferInfo, win32.Graphics.Direct3D11.ID3DX11FFT**ppFFT)
        {
            fixed (win32.Graphics.Direct3D11.D3DX11_FFT_BUFFER_INFO*pBufferInfoLocal = &pBufferInfo)
            {
                fixed (win32.Graphics.Direct3D11.D3DX11_FFT_DESC*pDescLocal = &pDesc)
                {
                    win32.System.Com.HRESULT __result = d3dcsx.D3DX11CreateFFT(pDeviceContext, pDescLocal, Flags, pBufferInfoLocal, ppFFT);
                    return __result;
                }
            }
        }

        /// <summary>Creates an ID3DX11FFT COM interface object.</summary>
        /// <param name = "pDeviceContext">
        /// <para>Type: <b><a href = "https://docs.microsoft.com/windows/desktop/api/d3d11/nn-d3d11-id3d11devicecontext">ID3D11DeviceContext</a>*</b></para>
        /// <para>A pointer to the <a href = "https://docs.microsoft.com/windows/desktop/api/d3d11/nn-d3d11-id3d11devicecontext">ID3D11DeviceContext</a> interface to use for the FFT.</para>
        /// <para><see href = "https://docs.microsoft.com/windows/win32/api//d3dcsx/nf-d3dcsx-d3dx11createfft#parameters">Read more on docs.microsoft.com</see>.</para>
        /// </param>
        /// <param name = "pDesc">
        /// <para>Type: <b>const <a href = "https://docs.microsoft.com/windows/desktop/api/d3dcsx/ns-d3dcsx-d3dx11_fft_desc">D3DX11_FFT_DESC</a>*</b></para>
        /// <para>A pointer to a <a href = "https://docs.microsoft.com/windows/desktop/api/d3dcsx/ns-d3dcsx-d3dx11_fft_desc">D3DX11_FFT_DESC</a> structure that describes the shape of the FFT data as well as the scaling factors that should be used for forward and inverse transforms.</para>
        /// <para><see href = "https://docs.microsoft.com/windows/win32/api//d3dcsx/nf-d3dcsx-d3dx11createfft#parameters">Read more on docs.microsoft.com</see>.</para>
        /// </param>
        /// <param name = "Flags">
        /// <para>Type: <b><a href = "https://docs.microsoft.com/windows/desktop/WinProg/windows-data-types">UINT</a></b></para>
        /// <para>Flags that affect the behavior of the FFT, can be 0 or a combination of flags from <a href = "https://docs.microsoft.com/windows/desktop/api/d3dcsx/ne-d3dcsx-d3dx11_fft_create_flag">D3DX11_FFT_CREATE_FLAG</a>.</para>
        /// <para><see href = "https://docs.microsoft.com/windows/win32/api//d3dcsx/nf-d3dcsx-d3dx11createfft#parameters">Read more on docs.microsoft.com</see>.</para>
        /// </param>
        /// <param name = "pBufferInfo">
        /// <para>Type: <b><a href = "https://docs.microsoft.com/windows/desktop/api/d3dcsx/ns-d3dcsx-d3dx11_fft_buffer_info">D3DX11_FFT_BUFFER_INFO</a>*</b></para>
        /// <para>A pointer to a <a href = "https://docs.microsoft.com/windows/desktop/api/d3dcsx/ns-d3dcsx-d3dx11_fft_buffer_info">D3DX11_FFT_BUFFER_INFO</a> structure that receives the buffer requirements to execute the FFT algorithms. Use this info to allocate raw buffers of the specified (or larger) sizes and then call the <a href = "https://docs.microsoft.com/windows/desktop/api/d3dcsx/nf-d3dcsx-id3dx11fft-attachbuffersandprecompute">ID3DX11FFT::AttachBuffersAndPrecompute</a> method to register the buffers with the FFT object.</para>
        /// <para><see href = "https://docs.microsoft.com/windows/win32/api//d3dcsx/nf-d3dcsx-d3dx11createfft#parameters">Read more on docs.microsoft.com</see>.</para>
        /// </param>
        /// <param name = "ppFFT">
        /// <para>Type: <b><a href = "https://docs.microsoft.com/windows/desktop/api/d3dcsx/nn-d3dcsx-id3dx11fft">ID3DX11FFT</a>**</b></para>
        /// <para>A pointer to a variable that receives a pointer to the <a href = "https://docs.microsoft.com/windows/desktop/api/d3dcsx/nn-d3dcsx-id3dx11fft">ID3DX11FFT</a> interface for the created FFT object.</para>
        /// <para><see href = "https://docs.microsoft.com/windows/win32/api//d3dcsx/nf-d3dcsx-d3dx11createfft#parameters">Read more on docs.microsoft.com</see>.</para>
        /// </param>
        /// <returns>
        /// <para>Type: <b><a href = "/windows/win32/com/structure-of-com-error-codes">HRESULT</a></b></para>
        /// <para>One of the <a href = "/windows/desktop/direct3d11/d3d11-graphics-reference-returnvalues">Direct3D 11 Return Codes</a>.</para>
        /// </returns>
        /// <remarks>
        /// <para><see href = "https://docs.microsoft.com/windows/win32/api//d3dcsx/nf-d3dcsx-d3dx11createfft">Learn more about this API from docs.microsoft.com</see>.</para>
        /// </remarks>
        [DllImport("d3dcsx", ExactSpelling = true)]
        internal static extern unsafe win32.System.Com.HRESULT D3DX11CreateFFT(win32.Graphics.Direct3D11.ID3D11DeviceContext*pDeviceContext, win32.Graphics.Direct3D11.D3DX11_FFT_DESC*pDesc, uint Flags, win32.Graphics.Direct3D11.D3DX11_FFT_BUFFER_INFO*pBufferInfo, win32.Graphics.Direct3D11.ID3DX11FFT**ppFFT);
        /// <inheritdoc cref = "D3DX11CreateFFT1DReal(win32.Graphics.Direct3D11.ID3D11DeviceContext*, uint, uint, win32.Graphics.Direct3D11.D3DX11_FFT_BUFFER_INFO*, win32.Graphics.Direct3D11.ID3DX11FFT**)"/>
        internal static unsafe win32.System.Com.HRESULT D3DX11CreateFFT1DReal(win32.Graphics.Direct3D11.ID3D11DeviceContext*pDeviceContext, uint X, uint Flags, out win32.Graphics.Direct3D11.D3DX11_FFT_BUFFER_INFO pBufferInfo, win32.Graphics.Direct3D11.ID3DX11FFT**ppFFT)
        {
            fixed (win32.Graphics.Direct3D11.D3DX11_FFT_BUFFER_INFO*pBufferInfoLocal = &pBufferInfo)
            {
                win32.System.Com.HRESULT __result = d3dcsx.D3DX11CreateFFT1DReal(pDeviceContext, X, Flags, pBufferInfoLocal, ppFFT);
                return __result;
            }
        }

        /// <summary>Creates an ID3DX11FFT COM interface object.</summary>
        /// <param name = "pDeviceContext">
        /// <para>Type: <b><a href = "https://docs.microsoft.com/windows/desktop/api/d3d11/nn-d3d11-id3d11devicecontext">ID3D11DeviceContext</a>*</b></para>
        /// <para>A pointer to the <a href = "https://docs.microsoft.com/windows/desktop/api/d3d11/nn-d3d11-id3d11devicecontext">ID3D11DeviceContext</a> interface to use for the FFT.</para>
        /// <para><see href = "https://docs.microsoft.com/windows/win32/api//d3dcsx/nf-d3dcsx-d3dx11createfft1dreal#parameters">Read more on docs.microsoft.com</see>.</para>
        /// </param>
        /// <param name = "X">
        /// <para>Type: <b><a href = "https://docs.microsoft.com/windows/desktop/WinProg/windows-data-types">UINT</a></b></para>
        /// <para>Length of the first dimension of the FFT.</para>
        /// <para><see href = "https://docs.microsoft.com/windows/win32/api//d3dcsx/nf-d3dcsx-d3dx11createfft1dreal#parameters">Read more on docs.microsoft.com</see>.</para>
        /// </param>
        /// <param name = "Flags">
        /// <para>Type: <b><a href = "https://docs.microsoft.com/windows/desktop/WinProg/windows-data-types">UINT</a></b></para>
        /// <para>Flags that affect the behavior of the FFT, can be 0 or a combination of flags from <a href = "https://docs.microsoft.com/windows/desktop/api/d3dcsx/ne-d3dcsx-d3dx11_fft_create_flag">D3DX11_FFT_CREATE_FLAG</a>.</para>
        /// <para><see href = "https://docs.microsoft.com/windows/win32/api//d3dcsx/nf-d3dcsx-d3dx11createfft1dreal#parameters">Read more on docs.microsoft.com</see>.</para>
        /// </param>
        /// <param name = "pBufferInfo">
        /// <para>Type: <b><a href = "https://docs.microsoft.com/windows/desktop/api/d3dcsx/ns-d3dcsx-d3dx11_fft_buffer_info">D3DX11_FFT_BUFFER_INFO</a>*</b></para>
        /// <para>A pointer to a <a href = "https://docs.microsoft.com/windows/desktop/api/d3dcsx/ns-d3dcsx-d3dx11_fft_buffer_info">D3DX11_FFT_BUFFER_INFO</a> structure that receives the buffer requirements to execute the FFT algorithms. Use this info to allocate raw buffers of the specified (or larger) sizes and then call the <a href = "https://docs.microsoft.com/windows/desktop/api/d3dcsx/nf-d3dcsx-id3dx11fft-attachbuffersandprecompute">ID3DX11FFT::AttachBuffersAndPrecompute</a> method to register the buffers with the FFT object.</para>
        /// <para><see href = "https://docs.microsoft.com/windows/win32/api//d3dcsx/nf-d3dcsx-d3dx11createfft1dreal#parameters">Read more on docs.microsoft.com</see>.</para>
        /// </param>
        /// <param name = "ppFFT">
        /// <para>Type: <b><a href = "https://docs.microsoft.com/windows/desktop/api/d3dcsx/nn-d3dcsx-id3dx11fft">ID3DX11FFT</a>**</b></para>
        /// <para>A pointer to a variable that receives a pointer to the <a href = "https://docs.microsoft.com/windows/desktop/api/d3dcsx/nn-d3dcsx-id3dx11fft">ID3DX11FFT</a> interface for the created FFT object.</para>
        /// <para><see href = "https://docs.microsoft.com/windows/win32/api//d3dcsx/nf-d3dcsx-d3dx11createfft1dreal#parameters">Read more on docs.microsoft.com</see>.</para>
        /// </param>
        /// <returns>
        /// <para>Type: <b><a href = "/windows/win32/com/structure-of-com-error-codes">HRESULT</a></b></para>
        /// <para>The return value is one of the values listed in <a href = "/windows/desktop/direct3d11/d3d11-graphics-reference-returnvalues">Direct3D 11 Return Codes</a>.</para>
        /// </returns>
        /// <remarks>
        /// <para><see href = "https://docs.microsoft.com/windows/win32/api//d3dcsx/nf-d3dcsx-d3dx11createfft1dreal">Learn more about this API from docs.microsoft.com</see>.</para>
        /// </remarks>
        [DllImport("d3dcsx", ExactSpelling = true)]
        internal static extern unsafe win32.System.Com.HRESULT D3DX11CreateFFT1DReal(win32.Graphics.Direct3D11.ID3D11DeviceContext*pDeviceContext, uint X, uint Flags, win32.Graphics.Direct3D11.D3DX11_FFT_BUFFER_INFO*pBufferInfo, win32.Graphics.Direct3D11.ID3DX11FFT**ppFFT);
        /// <inheritdoc cref = "D3DX11CreateFFT1DComplex(win32.Graphics.Direct3D11.ID3D11DeviceContext*, uint, uint, win32.Graphics.Direct3D11.D3DX11_FFT_BUFFER_INFO*, win32.Graphics.Direct3D11.ID3DX11FFT**)"/>
        internal static unsafe win32.System.Com.HRESULT D3DX11CreateFFT1DComplex(win32.Graphics.Direct3D11.ID3D11DeviceContext*pDeviceContext, uint X, uint Flags, out win32.Graphics.Direct3D11.D3DX11_FFT_BUFFER_INFO pBufferInfo, win32.Graphics.Direct3D11.ID3DX11FFT**ppFFT)
        {
            fixed (win32.Graphics.Direct3D11.D3DX11_FFT_BUFFER_INFO*pBufferInfoLocal = &pBufferInfo)
            {
                win32.System.Com.HRESULT __result = d3dcsx.D3DX11CreateFFT1DComplex(pDeviceContext, X, Flags, pBufferInfoLocal, ppFFT);
                return __result;
            }
        }

        /// <summary>Creates an ID3DX11FFT COM interface object.</summary>
        /// <param name = "pDeviceContext">
        /// <para>Type: <b><a href = "https://docs.microsoft.com/windows/desktop/api/d3d11/nn-d3d11-id3d11devicecontext">ID3D11DeviceContext</a>*</b></para>
        /// <para>A pointer to the <a href = "https://docs.microsoft.com/windows/desktop/api/d3d11/nn-d3d11-id3d11devicecontext">ID3D11DeviceContext</a> interface to use for the FFT.</para>
        /// <para><see href = "https://docs.microsoft.com/windows/win32/api//d3dcsx/nf-d3dcsx-d3dx11createfft1dcomplex#parameters">Read more on docs.microsoft.com</see>.</para>
        /// </param>
        /// <param name = "X">
        /// <para>Type: <b><a href = "https://docs.microsoft.com/windows/desktop/WinProg/windows-data-types">UINT</a></b></para>
        /// <para>Length of the first dimension of the FFT.</para>
        /// <para><see href = "https://docs.microsoft.com/windows/win32/api//d3dcsx/nf-d3dcsx-d3dx11createfft1dcomplex#parameters">Read more on docs.microsoft.com</see>.</para>
        /// </param>
        /// <param name = "Flags">
        /// <para>Type: <b><a href = "https://docs.microsoft.com/windows/desktop/WinProg/windows-data-types">UINT</a></b></para>
        /// <para>Flags that affect the behavior of the FFT, can be 0 or a combination of flags from <a href = "https://docs.microsoft.com/windows/desktop/api/d3dcsx/ne-d3dcsx-d3dx11_fft_create_flag">D3DX11_FFT_CREATE_FLAG</a>.</para>
        /// <para><see href = "https://docs.microsoft.com/windows/win32/api//d3dcsx/nf-d3dcsx-d3dx11createfft1dcomplex#parameters">Read more on docs.microsoft.com</see>.</para>
        /// </param>
        /// <param name = "pBufferInfo">
        /// <para>Type: <b><a href = "https://docs.microsoft.com/windows/desktop/api/d3dcsx/ns-d3dcsx-d3dx11_fft_buffer_info">D3DX11_FFT_BUFFER_INFO</a>*</b></para>
        /// <para>A pointer to a <a href = "https://docs.microsoft.com/windows/desktop/api/d3dcsx/ns-d3dcsx-d3dx11_fft_buffer_info">D3DX11_FFT_BUFFER_INFO</a> structure that receives the buffer requirements to execute the FFT algorithms. Use this info to allocate raw buffers of the specified (or larger) sizes and then call the <a href = "https://docs.microsoft.com/windows/desktop/api/d3dcsx/nf-d3dcsx-id3dx11fft-attachbuffersandprecompute">ID3DX11FFT::AttachBuffersAndPrecompute</a> method to register the buffers with the FFT object.</para>
        /// <para><see href = "https://docs.microsoft.com/windows/win32/api//d3dcsx/nf-d3dcsx-d3dx11createfft1dcomplex#parameters">Read more on docs.microsoft.com</see>.</para>
        /// </param>
        /// <param name = "ppFFT">
        /// <para>Type: <b><a href = "https://docs.microsoft.com/windows/desktop/api/d3dcsx/nn-d3dcsx-id3dx11fft">ID3DX11FFT</a>**</b></para>
        /// <para>A pointer to a variable that receives a pointer to the <a href = "https://docs.microsoft.com/windows/desktop/api/d3dcsx/nn-d3dcsx-id3dx11fft">ID3DX11FFT</a> interface for the created FFT object.</para>
        /// <para><see href = "https://docs.microsoft.com/windows/win32/api//d3dcsx/nf-d3dcsx-d3dx11createfft1dcomplex#parameters">Read more on docs.microsoft.com</see>.</para>
        /// </param>
        /// <returns>
        /// <para>Type: <b><a href = "/windows/win32/com/structure-of-com-error-codes">HRESULT</a></b></para>
        /// <para>The return value is one of the values listed in <a href = "/windows/desktop/direct3d11/d3d11-graphics-reference-returnvalues">Direct3D 11 Return Codes</a>.</para>
        /// </returns>
        /// <remarks>
        /// <para><see href = "https://docs.microsoft.com/windows/win32/api//d3dcsx/nf-d3dcsx-d3dx11createfft1dcomplex">Learn more about this API from docs.microsoft.com</see>.</para>
        /// </remarks>
        [DllImport("d3dcsx", ExactSpelling = true)]
        internal static extern unsafe win32.System.Com.HRESULT D3DX11CreateFFT1DComplex(win32.Graphics.Direct3D11.ID3D11DeviceContext*pDeviceContext, uint X, uint Flags, win32.Graphics.Direct3D11.D3DX11_FFT_BUFFER_INFO*pBufferInfo, win32.Graphics.Direct3D11.ID3DX11FFT**ppFFT);
        /// <inheritdoc cref = "D3DX11CreateFFT2DReal(win32.Graphics.Direct3D11.ID3D11DeviceContext*, uint, uint, uint, win32.Graphics.Direct3D11.D3DX11_FFT_BUFFER_INFO*, win32.Graphics.Direct3D11.ID3DX11FFT**)"/>
        internal static unsafe win32.System.Com.HRESULT D3DX11CreateFFT2DReal(win32.Graphics.Direct3D11.ID3D11DeviceContext*pDeviceContext, uint X, uint Y, uint Flags, out win32.Graphics.Direct3D11.D3DX11_FFT_BUFFER_INFO pBufferInfo, win32.Graphics.Direct3D11.ID3DX11FFT**ppFFT)
        {
            fixed (win32.Graphics.Direct3D11.D3DX11_FFT_BUFFER_INFO*pBufferInfoLocal = &pBufferInfo)
            {
                win32.System.Com.HRESULT __result = d3dcsx.D3DX11CreateFFT2DReal(pDeviceContext, X, Y, Flags, pBufferInfoLocal, ppFFT);
                return __result;
            }
        }

        /// <summary>Creates an ID3DX11FFT COM interface object.</summary>
        /// <param name = "pDeviceContext">
        /// <para>Type: <b><a href = "https://docs.microsoft.com/windows/desktop/api/d3d11/nn-d3d11-id3d11devicecontext">ID3D11DeviceContext</a>*</b></para>
        /// <para>A pointer to the <a href = "https://docs.microsoft.com/windows/desktop/api/d3d11/nn-d3d11-id3d11devicecontext">ID3D11DeviceContext</a> interface to use for the FFT.</para>
        /// <para><see href = "https://docs.microsoft.com/windows/win32/api//d3dcsx/nf-d3dcsx-d3dx11createfft2dreal#parameters">Read more on docs.microsoft.com</see>.</para>
        /// </param>
        /// <param name = "X">
        /// <para>Type: <b><a href = "https://docs.microsoft.com/windows/desktop/WinProg/windows-data-types">UINT</a></b></para>
        /// <para>Length of the first dimension of the FFT.</para>
        /// <para><see href = "https://docs.microsoft.com/windows/win32/api//d3dcsx/nf-d3dcsx-d3dx11createfft2dreal#parameters">Read more on docs.microsoft.com</see>.</para>
        /// </param>
        /// <param name = "Y">
        /// <para>Type: <b><a href = "https://docs.microsoft.com/windows/desktop/WinProg/windows-data-types">UINT</a></b></para>
        /// <para>Length of the second dimension of the FFT.</para>
        /// <para><see href = "https://docs.microsoft.com/windows/win32/api//d3dcsx/nf-d3dcsx-d3dx11createfft2dreal#parameters">Read more on docs.microsoft.com</see>.</para>
        /// </param>
        /// <param name = "Flags">
        /// <para>Type: <b><a href = "https://docs.microsoft.com/windows/desktop/WinProg/windows-data-types">UINT</a></b></para>
        /// <para>Flags that affect the behavior of the FFT, can be 0 or a combination of flags from <a href = "https://docs.microsoft.com/windows/desktop/api/d3dcsx/ne-d3dcsx-d3dx11_fft_create_flag">D3DX11_FFT_CREATE_FLAG</a>.</para>
        /// <para><see href = "https://docs.microsoft.com/windows/win32/api//d3dcsx/nf-d3dcsx-d3dx11createfft2dreal#parameters">Read more on docs.microsoft.com</see>.</para>
        /// </param>
        /// <param name = "pBufferInfo">
        /// <para>Type: <b><a href = "https://docs.microsoft.com/windows/desktop/api/d3dcsx/ns-d3dcsx-d3dx11_fft_buffer_info">D3DX11_FFT_BUFFER_INFO</a>*</b></para>
        /// <para>A pointer to a <a href = "https://docs.microsoft.com/windows/desktop/api/d3dcsx/ns-d3dcsx-d3dx11_fft_buffer_info">D3DX11_FFT_BUFFER_INFO</a> structure that receives the buffer requirements to execute the FFT algorithms. Use this info to allocate raw buffers of the specified (or larger) sizes and then call the <a href = "https://docs.microsoft.com/windows/desktop/api/d3dcsx/nf-d3dcsx-id3dx11fft-attachbuffersandprecompute">ID3DX11FFT::AttachBuffersAndPrecompute</a> method to register the buffers with the FFT object.</para>
        /// <para><see href = "https://docs.microsoft.com/windows/win32/api//d3dcsx/nf-d3dcsx-d3dx11createfft2dreal#parameters">Read more on docs.microsoft.com</see>.</para>
        /// </param>
        /// <param name = "ppFFT">
        /// <para>Type: <b><a href = "https://docs.microsoft.com/windows/desktop/api/d3dcsx/nn-d3dcsx-id3dx11fft">ID3DX11FFT</a>**</b></para>
        /// <para>A pointer to a variable that receives a pointer to the <a href = "https://docs.microsoft.com/windows/desktop/api/d3dcsx/nn-d3dcsx-id3dx11fft">ID3DX11FFT</a> interface for the created FFT object.</para>
        /// <para><see href = "https://docs.microsoft.com/windows/win32/api//d3dcsx/nf-d3dcsx-d3dx11createfft2dreal#parameters">Read more on docs.microsoft.com</see>.</para>
        /// </param>
        /// <returns>
        /// <para>Type: <b><a href = "/windows/win32/com/structure-of-com-error-codes">HRESULT</a></b></para>
        /// <para>The return value is one of the values listed in <a href = "/windows/desktop/direct3d11/d3d11-graphics-reference-returnvalues">Direct3D 11 Return Codes</a>.</para>
        /// </returns>
        /// <remarks>
        /// <para><see href = "https://docs.microsoft.com/windows/win32/api//d3dcsx/nf-d3dcsx-d3dx11createfft2dreal">Learn more about this API from docs.microsoft.com</see>.</para>
        /// </remarks>
        [DllImport("d3dcsx", ExactSpelling = true)]
        internal static extern unsafe win32.System.Com.HRESULT D3DX11CreateFFT2DReal(win32.Graphics.Direct3D11.ID3D11DeviceContext*pDeviceContext, uint X, uint Y, uint Flags, win32.Graphics.Direct3D11.D3DX11_FFT_BUFFER_INFO*pBufferInfo, win32.Graphics.Direct3D11.ID3DX11FFT**ppFFT);
        /// <inheritdoc cref = "D3DX11CreateFFT2DComplex(win32.Graphics.Direct3D11.ID3D11DeviceContext*, uint, uint, uint, win32.Graphics.Direct3D11.D3DX11_FFT_BUFFER_INFO*, win32.Graphics.Direct3D11.ID3DX11FFT**)"/>
        internal static unsafe win32.System.Com.HRESULT D3DX11CreateFFT2DComplex(win32.Graphics.Direct3D11.ID3D11DeviceContext*pDeviceContext, uint X, uint Y, uint Flags, out win32.Graphics.Direct3D11.D3DX11_FFT_BUFFER_INFO pBufferInfo, win32.Graphics.Direct3D11.ID3DX11FFT**ppFFT)
        {
            fixed (win32.Graphics.Direct3D11.D3DX11_FFT_BUFFER_INFO*pBufferInfoLocal = &pBufferInfo)
            {
                win32.System.Com.HRESULT __result = d3dcsx.D3DX11CreateFFT2DComplex(pDeviceContext, X, Y, Flags, pBufferInfoLocal, ppFFT);
                return __result;
            }
        }

        /// <summary>Creates an ID3DX11FFT COM interface object.</summary>
        /// <param name = "pDeviceContext">
        /// <para>Type: <b><a href = "https://docs.microsoft.com/windows/desktop/api/d3d11/nn-d3d11-id3d11devicecontext">ID3D11DeviceContext</a>*</b></para>
        /// <para>A pointer to the <a href = "https://docs.microsoft.com/windows/desktop/api/d3d11/nn-d3d11-id3d11devicecontext">ID3D11DeviceContext</a> interface to use for the FFT.</para>
        /// <para><see href = "https://docs.microsoft.com/windows/win32/api//d3dcsx/nf-d3dcsx-d3dx11createfft2dcomplex#parameters">Read more on docs.microsoft.com</see>.</para>
        /// </param>
        /// <param name = "X">
        /// <para>Type: <b><a href = "https://docs.microsoft.com/windows/desktop/WinProg/windows-data-types">UINT</a></b></para>
        /// <para>Length of the first dimension of the FFT.</para>
        /// <para><see href = "https://docs.microsoft.com/windows/win32/api//d3dcsx/nf-d3dcsx-d3dx11createfft2dcomplex#parameters">Read more on docs.microsoft.com</see>.</para>
        /// </param>
        /// <param name = "Y">
        /// <para>Type: <b><a href = "https://docs.microsoft.com/windows/desktop/WinProg/windows-data-types">UINT</a></b></para>
        /// <para>Length of the second dimension of the FFT.</para>
        /// <para><see href = "https://docs.microsoft.com/windows/win32/api//d3dcsx/nf-d3dcsx-d3dx11createfft2dcomplex#parameters">Read more on docs.microsoft.com</see>.</para>
        /// </param>
        /// <param name = "Flags">
        /// <para>Type: <b><a href = "https://docs.microsoft.com/windows/desktop/WinProg/windows-data-types">UINT</a></b></para>
        /// <para>Flags that affect the behavior of the FFT, can be 0 or a combination of flags from <a href = "https://docs.microsoft.com/windows/desktop/api/d3dcsx/ne-d3dcsx-d3dx11_fft_create_flag">D3DX11_FFT_CREATE_FLAG</a>.</para>
        /// <para><see href = "https://docs.microsoft.com/windows/win32/api//d3dcsx/nf-d3dcsx-d3dx11createfft2dcomplex#parameters">Read more on docs.microsoft.com</see>.</para>
        /// </param>
        /// <param name = "pBufferInfo">
        /// <para>Type: <b><a href = "https://docs.microsoft.com/windows/desktop/api/d3dcsx/ns-d3dcsx-d3dx11_fft_buffer_info">D3DX11_FFT_BUFFER_INFO</a>*</b></para>
        /// <para>A pointer to a <a href = "https://docs.microsoft.com/windows/desktop/api/d3dcsx/ns-d3dcsx-d3dx11_fft_buffer_info">D3DX11_FFT_BUFFER_INFO</a> structure that receives the buffer requirements to execute the FFT algorithms. Use this info to allocate raw buffers of the specified (or larger) sizes and then call the <a href = "https://docs.microsoft.com/windows/desktop/api/d3dcsx/nf-d3dcsx-id3dx11fft-attachbuffersandprecompute">ID3DX11FFT::AttachBuffersAndPrecompute</a> method to register the buffers with the FFT object.</para>
        /// <para><see href = "https://docs.microsoft.com/windows/win32/api//d3dcsx/nf-d3dcsx-d3dx11createfft2dcomplex#parameters">Read more on docs.microsoft.com</see>.</para>
        /// </param>
        /// <param name = "ppFFT">
        /// <para>Type: <b><a href = "https://docs.microsoft.com/windows/desktop/api/d3dcsx/nn-d3dcsx-id3dx11fft">ID3DX11FFT</a>**</b></para>
        /// <para>A pointer to a variable that receives a pointer to the <a href = "https://docs.microsoft.com/windows/desktop/api/d3dcsx/nn-d3dcsx-id3dx11fft">ID3DX11FFT</a> interface for the created FFT object.</para>
        /// <para><see href = "https://docs.microsoft.com/windows/win32/api//d3dcsx/nf-d3dcsx-d3dx11createfft2dcomplex#parameters">Read more on docs.microsoft.com</see>.</para>
        /// </param>
        /// <returns>
        /// <para>Type: <b><a href = "/windows/win32/com/structure-of-com-error-codes">HRESULT</a></b></para>
        /// <para>The return value is one of the values listed in <a href = "/windows/desktop/direct3d11/d3d11-graphics-reference-returnvalues">Direct3D 11 Return Codes</a>.</para>
        /// </returns>
        /// <remarks>
        /// <para><see href = "https://docs.microsoft.com/windows/win32/api//d3dcsx/nf-d3dcsx-d3dx11createfft2dcomplex">Learn more about this API from docs.microsoft.com</see>.</para>
        /// </remarks>
        [DllImport("d3dcsx", ExactSpelling = true)]
        internal static extern unsafe win32.System.Com.HRESULT D3DX11CreateFFT2DComplex(win32.Graphics.Direct3D11.ID3D11DeviceContext*pDeviceContext, uint X, uint Y, uint Flags, win32.Graphics.Direct3D11.D3DX11_FFT_BUFFER_INFO*pBufferInfo, win32.Graphics.Direct3D11.ID3DX11FFT**ppFFT);
        /// <inheritdoc cref = "D3DX11CreateFFT3DReal(win32.Graphics.Direct3D11.ID3D11DeviceContext*, uint, uint, uint, uint, win32.Graphics.Direct3D11.D3DX11_FFT_BUFFER_INFO*, win32.Graphics.Direct3D11.ID3DX11FFT**)"/>
        internal static unsafe win32.System.Com.HRESULT D3DX11CreateFFT3DReal(win32.Graphics.Direct3D11.ID3D11DeviceContext*pDeviceContext, uint X, uint Y, uint Z, uint Flags, out win32.Graphics.Direct3D11.D3DX11_FFT_BUFFER_INFO pBufferInfo, win32.Graphics.Direct3D11.ID3DX11FFT**ppFFT)
        {
            fixed (win32.Graphics.Direct3D11.D3DX11_FFT_BUFFER_INFO*pBufferInfoLocal = &pBufferInfo)
            {
                win32.System.Com.HRESULT __result = d3dcsx.D3DX11CreateFFT3DReal(pDeviceContext, X, Y, Z, Flags, pBufferInfoLocal, ppFFT);
                return __result;
            }
        }

        /// <summary>Creates an ID3DX11FFT COM interface object.</summary>
        /// <param name = "pDeviceContext">
        /// <para>Type: <b><a href = "https://docs.microsoft.com/windows/desktop/api/d3d11/nn-d3d11-id3d11devicecontext">ID3D11DeviceContext</a>*</b></para>
        /// <para>A pointer to the <a href = "https://docs.microsoft.com/windows/desktop/api/d3d11/nn-d3d11-id3d11devicecontext">ID3D11DeviceContext</a> interface to use for the FFT.</para>
        /// <para><see href = "https://docs.microsoft.com/windows/win32/api//d3dcsx/nf-d3dcsx-d3dx11createfft3dreal#parameters">Read more on docs.microsoft.com</see>.</para>
        /// </param>
        /// <param name = "X">
        /// <para>Type: <b><a href = "https://docs.microsoft.com/windows/desktop/WinProg/windows-data-types">UINT</a></b></para>
        /// <para>Length of the first dimension of the FFT.</para>
        /// <para><see href = "https://docs.microsoft.com/windows/win32/api//d3dcsx/nf-d3dcsx-d3dx11createfft3dreal#parameters">Read more on docs.microsoft.com</see>.</para>
        /// </param>
        /// <param name = "Y">
        /// <para>Type: <b><a href = "https://docs.microsoft.com/windows/desktop/WinProg/windows-data-types">UINT</a></b></para>
        /// <para>Length of the second dimension of the FFT.</para>
        /// <para><see href = "https://docs.microsoft.com/windows/win32/api//d3dcsx/nf-d3dcsx-d3dx11createfft3dreal#parameters">Read more on docs.microsoft.com</see>.</para>
        /// </param>
        /// <param name = "Z">
        /// <para>Type: <b><a href = "https://docs.microsoft.com/windows/desktop/WinProg/windows-data-types">UINT</a></b></para>
        /// <para>Length of the third dimension of the FFT.</para>
        /// <para><see href = "https://docs.microsoft.com/windows/win32/api//d3dcsx/nf-d3dcsx-d3dx11createfft3dreal#parameters">Read more on docs.microsoft.com</see>.</para>
        /// </param>
        /// <param name = "Flags">
        /// <para>Type: <b><a href = "https://docs.microsoft.com/windows/desktop/WinProg/windows-data-types">UINT</a></b></para>
        /// <para>Flags that affect the behavior of the FFT, can be 0 or a combination of flags from <a href = "https://docs.microsoft.com/windows/desktop/api/d3dcsx/ne-d3dcsx-d3dx11_fft_create_flag">D3DX11_FFT_CREATE_FLAG</a>.</para>
        /// <para><see href = "https://docs.microsoft.com/windows/win32/api//d3dcsx/nf-d3dcsx-d3dx11createfft3dreal#parameters">Read more on docs.microsoft.com</see>.</para>
        /// </param>
        /// <param name = "pBufferInfo">
        /// <para>Type: <b><a href = "https://docs.microsoft.com/windows/desktop/api/d3dcsx/ns-d3dcsx-d3dx11_fft_buffer_info">D3DX11_FFT_BUFFER_INFO</a>*</b></para>
        /// <para>A pointer to a <a href = "https://docs.microsoft.com/windows/desktop/api/d3dcsx/ns-d3dcsx-d3dx11_fft_buffer_info">D3DX11_FFT_BUFFER_INFO</a> structure that receives the buffer requirements to execute the FFT algorithms. Use this info to allocate raw buffers of the specified (or larger) sizes and then call the <a href = "https://docs.microsoft.com/windows/desktop/api/d3dcsx/nf-d3dcsx-id3dx11fft-attachbuffersandprecompute">ID3DX11FFT::AttachBuffersAndPrecompute</a> method to register the buffers with the FFT object.</para>
        /// <para><see href = "https://docs.microsoft.com/windows/win32/api//d3dcsx/nf-d3dcsx-d3dx11createfft3dreal#parameters">Read more on docs.microsoft.com</see>.</para>
        /// </param>
        /// <param name = "ppFFT">
        /// <para>Type: <b><a href = "https://docs.microsoft.com/windows/desktop/api/d3dcsx/nn-d3dcsx-id3dx11fft">ID3DX11FFT</a>**</b></para>
        /// <para>A pointer to a variable that receives a pointer to the <a href = "https://docs.microsoft.com/windows/desktop/api/d3dcsx/nn-d3dcsx-id3dx11fft">ID3DX11FFT</a> interface for the created FFT object.</para>
        /// <para><see href = "https://docs.microsoft.com/windows/win32/api//d3dcsx/nf-d3dcsx-d3dx11createfft3dreal#parameters">Read more on docs.microsoft.com</see>.</para>
        /// </param>
        /// <returns>
        /// <para>Type: <b><a href = "/windows/win32/com/structure-of-com-error-codes">HRESULT</a></b></para>
        /// <para>The return value is one of the values listed in <a href = "/windows/desktop/direct3d11/d3d11-graphics-reference-returnvalues">Direct3D 11 Return Codes</a>.</para>
        /// </returns>
        /// <remarks>
        /// <para><see href = "https://docs.microsoft.com/windows/win32/api//d3dcsx/nf-d3dcsx-d3dx11createfft3dreal">Learn more about this API from docs.microsoft.com</see>.</para>
        /// </remarks>
        [DllImport("d3dcsx", ExactSpelling = true)]
        internal static extern unsafe win32.System.Com.HRESULT D3DX11CreateFFT3DReal(win32.Graphics.Direct3D11.ID3D11DeviceContext*pDeviceContext, uint X, uint Y, uint Z, uint Flags, win32.Graphics.Direct3D11.D3DX11_FFT_BUFFER_INFO*pBufferInfo, win32.Graphics.Direct3D11.ID3DX11FFT**ppFFT);
        /// <inheritdoc cref = "D3DX11CreateFFT3DComplex(win32.Graphics.Direct3D11.ID3D11DeviceContext*, uint, uint, uint, uint, win32.Graphics.Direct3D11.D3DX11_FFT_BUFFER_INFO*, win32.Graphics.Direct3D11.ID3DX11FFT**)"/>
        internal static unsafe win32.System.Com.HRESULT D3DX11CreateFFT3DComplex(win32.Graphics.Direct3D11.ID3D11DeviceContext*pDeviceContext, uint X, uint Y, uint Z, uint Flags, out win32.Graphics.Direct3D11.D3DX11_FFT_BUFFER_INFO pBufferInfo, win32.Graphics.Direct3D11.ID3DX11FFT**ppFFT)
        {
            fixed (win32.Graphics.Direct3D11.D3DX11_FFT_BUFFER_INFO*pBufferInfoLocal = &pBufferInfo)
            {
                win32.System.Com.HRESULT __result = d3dcsx.D3DX11CreateFFT3DComplex(pDeviceContext, X, Y, Z, Flags, pBufferInfoLocal, ppFFT);
                return __result;
            }
        }

        /// <summary>Creates an ID3DX11FFT COM interface object.</summary>
        /// <param name = "pDeviceContext">
        /// <para>Type: <b><a href = "https://docs.microsoft.com/windows/desktop/api/d3d11/nn-d3d11-id3d11devicecontext">ID3D11DeviceContext</a>*</b></para>
        /// <para>A pointer to the <a href = "https://docs.microsoft.com/windows/desktop/api/d3d11/nn-d3d11-id3d11devicecontext">ID3D11DeviceContext</a> interface to use for the FFT.</para>
        /// <para><see href = "https://docs.microsoft.com/windows/win32/api//d3dcsx/nf-d3dcsx-d3dx11createfft3dcomplex#parameters">Read more on docs.microsoft.com</see>.</para>
        /// </param>
        /// <param name = "X">
        /// <para>Type: <b><a href = "https://docs.microsoft.com/windows/desktop/WinProg/windows-data-types">UINT</a></b></para>
        /// <para>Length of the first dimension of the FFT.</para>
        /// <para><see href = "https://docs.microsoft.com/windows/win32/api//d3dcsx/nf-d3dcsx-d3dx11createfft3dcomplex#parameters">Read more on docs.microsoft.com</see>.</para>
        /// </param>
        /// <param name = "Y">
        /// <para>Type: <b><a href = "https://docs.microsoft.com/windows/desktop/WinProg/windows-data-types">UINT</a></b></para>
        /// <para>Length of the second dimension of the FFT.</para>
        /// <para><see href = "https://docs.microsoft.com/windows/win32/api//d3dcsx/nf-d3dcsx-d3dx11createfft3dcomplex#parameters">Read more on docs.microsoft.com</see>.</para>
        /// </param>
        /// <param name = "Z">
        /// <para>Type: <b><a href = "https://docs.microsoft.com/windows/desktop/WinProg/windows-data-types">UINT</a></b></para>
        /// <para>Length of the third dimension of the FFT.</para>
        /// <para><see href = "https://docs.microsoft.com/windows/win32/api//d3dcsx/nf-d3dcsx-d3dx11createfft3dcomplex#parameters">Read more on docs.microsoft.com</see>.</para>
        /// </param>
        /// <param name = "Flags">
        /// <para>Type: <b><a href = "https://docs.microsoft.com/windows/desktop/WinProg/windows-data-types">UINT</a></b></para>
        /// <para>Flags that affect the behavior of the FFT, can be 0 or a combination of flags from <a href = "https://docs.microsoft.com/windows/desktop/api/d3dcsx/ne-d3dcsx-d3dx11_fft_create_flag">D3DX11_FFT_CREATE_FLAG</a>.</para>
        /// <para><see href = "https://docs.microsoft.com/windows/win32/api//d3dcsx/nf-d3dcsx-d3dx11createfft3dcomplex#parameters">Read more on docs.microsoft.com</see>.</para>
        /// </param>
        /// <param name = "pBufferInfo">
        /// <para>Type: <b><a href = "https://docs.microsoft.com/windows/desktop/api/d3dcsx/ns-d3dcsx-d3dx11_fft_buffer_info">D3DX11_FFT_BUFFER_INFO</a>*</b></para>
        /// <para>A pointer to a <a href = "https://docs.microsoft.com/windows/desktop/api/d3dcsx/ns-d3dcsx-d3dx11_fft_buffer_info">D3DX11_FFT_BUFFER_INFO</a> structure that receives the buffer requirements to execute the FFT algorithms. Use this info to allocate raw buffers of the specified (or larger) sizes and then call the <a href = "https://docs.microsoft.com/windows/desktop/api/d3dcsx/nf-d3dcsx-id3dx11fft-attachbuffersandprecompute">ID3DX11FFT::AttachBuffersAndPrecompute</a> method to register the buffers with the FFT object.</para>
        /// <para><see href = "https://docs.microsoft.com/windows/win32/api//d3dcsx/nf-d3dcsx-d3dx11createfft3dcomplex#parameters">Read more on docs.microsoft.com</see>.</para>
        /// </param>
        /// <param name = "ppFFT">
        /// <para>Type: <b><a href = "https://docs.microsoft.com/windows/desktop/api/d3dcsx/nn-d3dcsx-id3dx11fft">ID3DX11FFT</a>**</b></para>
        /// <para>A pointer to a variable that receives a pointer to the <a href = "https://docs.microsoft.com/windows/desktop/api/d3dcsx/nn-d3dcsx-id3dx11fft">ID3DX11FFT</a> interface for the created FFT object.</para>
        /// <para><see href = "https://docs.microsoft.com/windows/win32/api//d3dcsx/nf-d3dcsx-d3dx11createfft3dcomplex#parameters">Read more on docs.microsoft.com</see>.</para>
        /// </param>
        /// <returns>
        /// <para>Type: <b><a href = "/windows/win32/com/structure-of-com-error-codes">HRESULT</a></b></para>
        /// <para>The return value is one of the values listed in <a href = "/windows/desktop/direct3d11/d3d11-graphics-reference-returnvalues">Direct3D 11 Return Codes</a>.</para>
        /// </returns>
        /// <remarks>
        /// <para><see href = "https://docs.microsoft.com/windows/win32/api//d3dcsx/nf-d3dcsx-d3dx11createfft3dcomplex">Learn more about this API from docs.microsoft.com</see>.</para>
        /// </remarks>
        [DllImport("d3dcsx", ExactSpelling = true)]
        internal static extern unsafe win32.System.Com.HRESULT D3DX11CreateFFT3DComplex(win32.Graphics.Direct3D11.ID3D11DeviceContext*pDeviceContext, uint X, uint Y, uint Z, uint Flags, win32.Graphics.Direct3D11.D3DX11_FFT_BUFFER_INFO*pBufferInfo, win32.Graphics.Direct3D11.ID3DX11FFT**ppFFT);
    }
}