// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable CS1591, CS1573, CS0465, CS0649, CS8019, CS1570, CS1584, CS1658
namespace Windows.Win32
{
    using global::System;
    using global::System.Diagnostics;
    using global::System.Runtime.CompilerServices;
    using global::System.Runtime.InteropServices;
    using win32 = global::Windows.Win32;

    namespace Storage.Packaging.Appx
    {
        /// <summary>The AppPolicyLifecycleManagement enumeration indicates whether a process is lifecycle-managed or not.</summary>
        /// <remarks>
        /// <para><see href = "https://docs.microsoft.com/windows/win32/api//appmodel/ne-appmodel-apppolicylifecyclemanagement">Learn more about this API from docs.microsoft.com</see>.</para>
        /// </remarks>
        internal enum AppPolicyLifecycleManagement
        {
            /// <summary>Indicates that the process's lifecycle is not managed.</summary>
            AppPolicyLifecycleManagement_Unmanaged = 0,
            /// <summary>Indicates that the process's  lifecycle is managed by Process Lifecycle Manager (PLM).</summary>
            AppPolicyLifecycleManagement_Managed = 1,
        }
    }
}